import re

__FRAUD_DBI = re.compile(rb"(?:\bdollars?\b|\busd(?:ollars)?(?:[0-9]|\b)|\bus\$|\$[0-9,.]{6,}|\$[0-9].{0,8}[mb]illion|\$[0-9.,]{2,10} ?m|\beuros?\b|u[.]?s[.]? [0-9.]+ m)", re.IGNORECASE)
__FRAUD_KJV = re.compile(rb"(?:claim|concerning) (?:the|this) money", re.IGNORECASE)
__FRAUD_IRJ = re.compile(rb"(?:finance|holding|securit(?:ies|y)) (?:company|firm|storage house)", re.IGNORECASE)
__FRAUD_NEB = re.compile(rb"(?:government|bank) ofnigeria", re.IGNORECASE)
__FRAUD_XJR = re.compile(rb"(?:who wasa|as a|an? honest|youbeing a|to any) foreigner", re.IGNORECASE)
__FRAUD_DPR = re.compile(rb"\b(?:(?:respond|reply)(?:urgently|immediately)|(?:urgent|immediate|earliest)(?:reply|response))\b", re.IGNORECASE)
__FRAUD_PTS = re.compile(rb"\b(?:ass?ass?inat(?:ed|ion)|murder(?:e?d)?|kill(?:ed|ing)\b[^.]{0,99}\b(?:war veterans|rebels?))\b", re.IGNORECASE)
__FRAUD_BEP = re.compile(rb"\b(?:bank ofnigeria|centralbank of|trustbank|apexbank|amalgamatedbank)\b", re.IGNORECASE)
__FRAUD_TDP = re.compile(rb"\b(?:business partner(?:s|ship)?|silentpartner(?:s|ship)?)\b", re.IGNORECASE)
__FRAUD_GAN = re.compile(rb"\b(?:charles taylor|serena|abacha|sese[-]?seko|kabila)\b", re.IGNORECASE)
__FRAUD_IRT = re.compile(rb"\b(?:compliments? ofthe|dearfriend|dear sir|yoursfaithfully|season'?s greetings)\b", re.IGNORECASE)
__FRAUD_AON = re.compile(rb"\b(?:confidential|private|alternate|alternative)(?:(?:e-? *)?mail)\b", re.IGNORECASE)
__FRAUD_WNY = re.compile(rb"\b(?:disburse?(?:ment)?|incurr?(?:ed)?|remunerr?at(?:ed?|ion)|remm?itt?(?:ed|ance|ing)?)\b", re.IGNORECASE)
__FRAUD_IPK = re.compile(rb"\b(?:in|to|visit) yourcountry\b", re.IGNORECASE)
__FRAUD_QXX = re.compile(rb"\b(?:my nameis|iam)(?:mrs?|engr|barrister|dr|prince(?:ss)?)[. ]", re.IGNORECASE)
__FRAUD_IOU = re.compile(rb"\b(?:no risks?|risk-? *free|free of risks?|100% safe)\b", re.IGNORECASE)
__FRAUD_EZY = re.compile(rb"\b(?:of|the) late president\b", re.IGNORECASE)
__FRAUD_MLY = re.compile(rb"\b(?:reply|respond)\b[^.]{0,50}\b(?:to|through)\b[^.]{0,50}\@\b", re.IGNORECASE)
__FRAUD_ZFJ = re.compile(rb"\b(?:wife|son|brother|daughter) ofthelate\b", re.IGNORECASE)
__FRAUD_KDT = re.compile(rb"\bU\.?S\.?(?:D\.?)?\s*(?:\$\s*)?(?:\d+,\d+,\d+|\d+\.\d+\.\d+|\d+(?:\.\d+)?\s*milli?on)", re.IGNORECASE)
__FRAUD_ULK = re.compile(rb"\baffidavits?\b", re.IGNORECASE)
__FRAUD_BGP = re.compile(rb"\battached toticketnumber\b", re.IGNORECASE)
__FRAUD_FBI = re.compile(rb"\bdisburs", re.IGNORECASE)
__FRAUD_JBU = re.compile(rb"\bforeign account\b", re.IGNORECASE)
__FRAUD_YWW = re.compile(rb"\bfurnish youwith\b", re.IGNORECASE)
__FRAUD_JYG = re.compile(rb"\bgive\s+you.{0,15}(?:fund|money|total|sum|contact|percent)\b", re.IGNORECASE)
__FRAUD_XVW = re.compile(rb"\bhonest cooperation\b", re.IGNORECASE)
__FRAUD_UUY = re.compile(rb"\blegitimate business(?:es)?\b", re.IGNORECASE)
__FRAUD_SNT = re.compile(rb"\blocate(?: .{1,20})? extended relative", re.IGNORECASE)
__FRAUD_LTX = re.compile(rb"\bmilli?on (?:.{1,25} thousand\s*)?(?:(?:unitedstates|u\.?s\.?)dollars|(?:U\.?S\.?D?))\b", re.IGNORECASE)
__FRAUD_JNB = re.compile(rb"\boperat(?:e|ing)\b[^.]{0,99}\b(?:for(?:ei|ie)gn|off-??shore|over-??seas?)(?:bank )?accounts?\b", re.IGNORECASE)
__FRAUD_QFY = re.compile(rb"\bover-?(?:invoiced?|cost(?:s|ing)?)\b", re.IGNORECASE)
__FRAUD_WDR = re.compile(rb"\bprivate lawyer\b", re.IGNORECASE)
__FRAUD_WFC = re.compile(rb"\bsecur(?:e|ing)(?:the )?(?:funds?|monies)\b", re.IGNORECASE)
__FRAUD_AUM = re.compile(rb"\bthe desk of\b", re.IGNORECASE)
__FRAUD_MCQ = re.compile(rb"\btransaction\b.{1,30}\b(?:magnitude|diplomatic|strict|absolute|secret|confiden(?:tial|ce)|guarantee)", re.IGNORECASE)
__FRAUD_ETX = re.compile(rb"\byour\b[^.]{0,99}\b(?:contact (?:details|information)|private (?:e?[- ]?mail|telephone|tel|phone|fax))\b", re.IGNORECASE)
__FRAUD_PVN = re.compile(rb"as thebeneficiary", re.IGNORECASE)
__FRAUD_FVU = re.compile(rb"award notification", re.IGNORECASE)
__FRAUD_CKF = re.compile(rb"computer ballot system", re.IGNORECASE)
__FRAUD_FCW = re.compile(rb"fiduciary agent", re.IGNORECASE)
__FRAUD_MQO = re.compile(rb"foreign (?:business partner|customer)", re.IGNORECASE)
__FRAUD_TCC = re.compile(rb"foreign(?:offshore )?(?:bank|account)", re.IGNORECASE)
__FRAUD_GBW = re.compile(rb"god gives.{1,10}second chance", re.IGNORECASE)
__FRAUD_NRG = re.compile(rb"i am contacting you", re.IGNORECASE)
__FRAUD_RLX = re.compile(rb"lott(?:o|ery)(?:co,?ordinator|international)", re.IGNORECASE)
__FRAUD_AXF = re.compile(rb"magnanimity", re.IGNORECASE)
__FRAUD_THJ = re.compile(rb"modalit(?:y|ies)", re.IGNORECASE)
__FRAUD_YQV = re.compile(rb"nigerian?(?:national|government)", re.IGNORECASE)
__FRAUD_YJA = re.compile(rb"over-invoice", re.IGNORECASE)
__FRAUD_YPO = re.compile(rb"the totalsum", re.IGNORECASE)
__FRAUD_UOQ = re.compile(rb"vital documents", re.IGNORECASE)
GTUBE = re.compile(rb"XJS\*C4JDBQADN1\.NSBN3\*2IDNEN\*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL\*C\.34X", re.IGNORECASE)
TRACKER_ID = re.compile(rb"^[a-z0-9]{6,24}[-_a-z0-9]{12,36}[a-z0-9]{6,24}\s*/is", re.IGNORECASE)
WEIRD_QUOTING = re.compile(rb"[\042\223\224\262\263\271]{2}\S{0,16}[\042\223\224\262\263\271]{2}", re.IGNORECASE)
EMAIL_ROT13 = re.compile(rb"\b[a-z(\]-]+\^[a-z-]+\([a-z]{2,3}\b", re.IGNORECASE)
__LONGWORDS_A = re.compile(rb"\b(?:[a-z]{8,}[\s\.]+){6}", re.IGNORECASE)
__LONGWORDS_B = re.compile(rb"\b(?:[a-z]{6,}[\s\.]+){9}", re.IGNORECASE)
__LONGWORDS_C = re.compile(rb"\b(?:[a-z]{5,}[\s\.]+){10}", re.IGNORECASE)












DRUG_DOSAGE = re.compile(rb"m{[\d\.]+\$? *(?:[\\/]|per) *d.?o.?s.?e}i", re.IGNORECASE)
DRUG_ED_CAPS = re.compile(rb"\b(?:CIALIS|LEVITRA|VIAGRA)", re.IGNORECASE)
DRUG_ED_SILD = re.compile(rb"\bsildenafil\b", re.IGNORECASE)
DRUG_ED_GENERIC = re.compile(rb"\bGeneric Viagra\b", re.IGNORECASE)
DRUG_ED_ONLINE = re.compile(rb"\bviagra.{0,25}(?:express|online|overnight)", re.IGNORECASE)
ONLINE_PHARMACY = re.compile(rb"\bonline pharmacy|\b(?:drugs|medications)online", re.IGNORECASE)
NO_PRESCRIPTION = re.compile(rb"N[o0].{1,10}P(?:er|re)scr[i1]pt[i1][o0]n.{1,10}(?:n[e3][e3]d[e3]d|requ[1i]re|n[e3]c[e3]ssary)", re.IGNORECASE)
VIA_GAP_GRA = re.compile(rb"\bvia.gra\b", re.IGNORECASE)
__DRUGS_ERECTILE_V = re.compile(rb"\bViagra\b", re.IGNORECASE)
__DRUGS_ERECTILE_C = re.compile(rb"\bCialis\b", re.IGNORECASE)
__DRUGS_ERECTILE_L = re.compile(rb"\bLevitra\b", re.IGNORECASE)
__DRUGS_ERECTILE1 = re.compile(rb"(?:\b|\s)[_\W]{0,3}(?:\\\/|V)[_\W]{0,3}[ij1!|l\xEC\xED\xEE\xEF][_\W]{0,3}[a40\xE0-\xE6@][_\W]{0,3}[xyz]?[gj][_\W]{0,3}r[_\W]{0,3}[a40\xE0-\xE6@][_\W]{0,3}x?[_\W]{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_ERECTILE2 = re.compile(rb"\bV(?:agira|igara|iaggra|iaegra)\b", re.IGNORECASE)
__DRUGS_ERECTILE3 = re.compile(rb"(?:\A|[\s\x00-\x2f\x3a-\x40\x5b-\x60\x7b-\x7f])[_\W]{0,3}C[_\W]{0,3}[ij1!|l\xEC\xED\xEE\xEF][_\W]{0,3}[a4\xE0-\xE6@][_\W]{0,3}l?[l!|1][_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}s[_\W]{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_ERECTILE4 = re.compile(rb"\bC(?:alis|ilias|ilais)\b", re.IGNORECASE)
__DRUGS_ERECTILE5 = re.compile(rb"\b_{0,3}s[_\W]?[i1!|l\xEC-\xEF][_\W]?l[_\W]?d[_\W]?[e3\xE8-\xEB][_\W]?n[_\W]?[a4\xE0-\xE6@][_\W]?f[_\W]?[i1!|l\xEC-\xEF][_\W]?l c[_\W]?[i1!|l\xEC-\xEF][_\W]?t[_\W]?r[_\W]?[a4\xE0-\xE6@][_\W]?t[_\W]?[e3\xE8-\xEB]_{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_ERECTILE6 = re.compile(rb"\b_{0,3}L[_\W]?[e3\xE8-\xEB][_\W]?(?:\\\/|V)[_\W]?[i1!|l\xEC-\xEF][_\W]?t[_\W]?r[_\W]?[a4\xE0-\xE6@][_\W]?(?:\b|\s)", re.IGNORECASE)
__DRUGS_ERECTILE8 = re.compile(rb"\b_{0,3}T[_\W]?[a4\xE0-\xE6@][_\W]?d[_\W]?[a4\xE0-\xE6@][_\W]?l[_\W]?[a4\xE0-\xE6@][_\W]?f[_\W]?[i1!|l\xEC-\xEF][_\W]?l_{0,3}\b", re.IGNORECASE)
__DRUGS_ERECTILE11 = re.compile(rb"(?:\b|\s)_{0,3}[a4\xE0-\xE6@][_\W]{0,3}p[_\W]{0,3}c[_\W]{0,3}[a4\xE0-\xE6@][_\W]{0,3}[l!|1][_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}s_{0,3}\b", re.IGNORECASE)
__DRUGS_DIET_PHEN = re.compile(rb"\bphentermine\b", re.IGNORECASE)
__DRUGS_DIET1 = re.compile(rb"(?:\b|\s)[_\W]{0,3}p[_\W]{0,3}h[_\W]{0,3}[e3\xE8-\xEB][_\W]{0,3}n[_\W]{0,3}t[_\W]{0,3}[e3\xE8-\xEB][_\W]{0,3}r[_\W]{0,3}m[_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}n[_\W]{0,3}[e3\xE8-\xEB][_\W]{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_DIET2 = re.compile(rb"(?:\b|\s)_{0,3}[i1!|l\xEC-\xEF][_\W]?o[_\W]?n[_\W]?[a4\xE0-\xE6@][_\W]?m[_\W]?[i1!|l\xEC-\xEF][_\W]?n_{0,3}\b", re.IGNORECASE)
__DRUGS_DIET3 = re.compile(rb"\bbontril\b", re.IGNORECASE)
__DRUGS_DIET4 = re.compile(rb"\bphendimetrazine\b", re.IGNORECASE)
__DRUGS_DIET5 = re.compile(rb"\bdiethylpropion\b", re.IGNORECASE)
__DRUGS_DIET6 = re.compile(rb"(?:\b|\s)[_\W]{0,3}M[_\W]{0,3}[e3\xE8-\xEB][_\W]{0,3}r[_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}d[_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}[a4\xE0-\xE6@][_\W]{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_DIET7 = re.compile(rb"\b_{0,3}t[_\W]?[e3\xE8-\xEB][_\W]?n[_\W]?u[_\W]?a[_\W]?t[_\W]?[e3\xE8-\xEB]_{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_DIET8 = re.compile(rb"\b_{0,3}d[_\W]?[i1!|l\xEC-\xEF][_\W]?d[_\W]?r[_\W][e3\xE8-\xEB[_\W]?xx?_{0,3}\b", re.IGNORECASE)
__DRUGS_DIET9 = re.compile(rb"\b_{0,3}a[_\W]?d[_\W]?[i1!|l\xEC-\xEF][_\W]?p[_\W]?[e3\xE8-\xEB][_\W]?x_{0,3}\b", re.IGNORECASE)
__DRUGS_DIET10 = re.compile(rb"\b_{0,3}x?x[_\W]?[e3\xE8-\xEB][_\W]?n[_\W]?[i1!|l\xEC-\xEF][_\W]?c[_\W]?[a4\xE0-\xE6@][_\W]?l_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN_VICO = re.compile(rb"vicodin", re.IGNORECASE)
__DRUGS_PAIN_VIOXX = re.compile(rb"vioxx", re.IGNORECASE)
__DRUGS_PAIN_FIO = re.compile(rb"fioricet", re.IGNORECASE)
__DRUGS_PAIN1 = re.compile(rb"\b_{0,3}h[_\W]?y[_\W]?d[_\W]?r[_\W]?[o0\xF2-\xF6][_\W]?c[_\W]?[o0\xF2-\xF6][_\W]?d[_\W]?[o0\xF2-\xF6][_\W]?n[_\W]?e_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN2 = re.compile(rb"\b_{0,3}c[o0\xF2-\xF6]deine_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN3 = re.compile(rb"(?:\b|\s)[_\W]{0,3}[u\xB5\xF9-\xFC][_\W]{0,3}l[_\W]{0,3}t[_\W]{0,3}r[_\W]{0,3}[a4\xE0-\xE6@][_\W]{0,3}m_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN4 = re.compile(rb"(?:\b|\s)[_\W]{0,3}(?:\\\/|V)[_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}c[_\W]{0,3}[o0\xF2-\xF6][_\W]{0,3}d[_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}ns?[_\W]{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_PAIN5 = re.compile(rb"\b_{0,3}t[_\W]?r[_\W]?[a4\xE0-\xE6@][_\W]?m[_\W]?[a4\xE0-\xE6@][_\W]?d[_\W]?[o0\xF2-\xF6][_\W]?[l!|1]_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN6 = re.compile(rb"\b_{0,3}u[_\W]?l[_\W]?t[_\W]?r[_\W]?a[_\W]?c[_\W]?e[_\W]?t_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN7 = re.compile(rb"\b_{0,3}f[_\W]?[i1!|l\xEC-\xEF][_\W]?[o0\xF2-\xF6][_\W]?r[_\W]?[i1!|l\xEC-\xEF][_\W]?c[_\W]?[e3\xE8-\xEB][_\W]?[t7]_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN8 = re.compile(rb"\b_{0,3}c[_\W]?[e3\xE8-\xEB][_\W]?l[_\W]?[e3\xE8-\xEB][_\W]?b[_\W]?r[_\W]?[e3\xE8-\xEB][_\W]?x_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN9 = re.compile(rb"(?:\b|\s)_{0,3}[i1!|l\xEC-\xEF]m[i1!|l\xEC-\xEF]tr[e3\xE8-\xEB]x_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN10 = re.compile(rb"(?:\b|\s)[_\W]{0,3}(?:\\\/|V)[_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}[o0\xF2-\xF6][_\W]{0,3}x[_\W]{0,3}xx?_{0,3}\b", re.IGNORECASE)
__DRUGS_PAIN11 = re.compile(rb"\bzebutal\b", re.IGNORECASE)
__DRUGS_PAIN12 = re.compile(rb"\besgic plus\b", re.IGNORECASE)
__DRUGS_PAIN13 = re.compile(rb"\bD[_\W]?[a4\xE0-\xE6@][_\W]?r[_\W]?v[_\W]?[o0\xF2-\xF6][_\W]?n\b", re.IGNORECASE)
__DRUGS_PAIN14 = re.compile(rb"N[o0\xF2-\xF6]rc[o0\xF2-\xF6]", re.IGNORECASE)
__DRUGS_SLEEP1 = re.compile(rb"(?:\b|\s)[_\W]{0,3}[a4\xE0-\xE6@][_\W]{0,3}m[_\W]{0,3}b[_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}[e3\xE8-\xEB][_\W]{0,3}n[_\W]{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_SLEEP2 = re.compile(rb"(?:\b|\s)[_\W]{0,3}S[_\W]{0,3}[o0\xF2-\xF6][_\W]{0,3}n[_\W]{0,3}[a4\xE0-\xE6@][_\W]{0,3}t[_\W]{0,3}[a4\xE0-\xE6@][_\W]{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_SLEEP3 = re.compile(rb"\b_{0,3}R[_\W]?[e3\xE8-\xEB][_\W]?s[_\W]?t[_\W]?[o0\xF2-\xF6][_\W]?r[_\W]?i[_\W]?l_{0,3}\b", re.IGNORECASE)
__DRUGS_SLEEP4 = re.compile(rb"\b_{0,3}H[_\W]?[a4\xE0-\xE6@][_\W]?l[_\W]?c[_\W]?i[_\W]?[o0\xF2-\xF6][_\W]?n_{0,3}\b", re.IGNORECASE)
__DRUGS_MUSCLE1 = re.compile(rb"(?:\b|\s)[_\W]{0,3}s[_\W]{0,3}[o0\xF2-\xF6][_\W]{0,3}m[_\W]{0,3}[a4\xE0-\xE3\xE5\xE6@][_\W]{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_MUSCLE2 = re.compile(rb"\b_{0,3}cycl[o0\xF2-\xF6]b[e3\xE8-\xEB]nz[a4\xE0-\xE6@]pr[i1!|l\xEC-\xEF]n[e3\xE8-\xEB]_{0,3}(?:\b|\s)", re.IGNORECASE)
__DRUGS_MUSCLE3 = re.compile(rb"\b_{0,3}f[_\W]?l[_\W]?[e3\xE8-\xEB][_\W]?x[_\W]?[e3\xE8-\xEB][_\W]?r[_\W]?[i1!|l\xEC-\xEF]_{0,3}[_\W]?l_{0,3}\b", re.IGNORECASE)
__DRUGS_MUSCLE4 = re.compile(rb"\b_{0,3}z[_\W]?a[_\W]?n[_\W]?a[_\W]?f[_\W]?l[_\W]?e[_\W]?x_{0,3}\b", re.IGNORECASE)
__DRUGS_MUSCLE5 = re.compile(rb"\bskelaxin\b", re.IGNORECASE)
__DRUGS_ANXIETY_XAN = re.compile(rb"xan[ae]x", re.IGNORECASE)
__DRUGS_ANXIETY_VAL = re.compile(rb"valium", re.IGNORECASE)
__DRUGS_ANXIETY1 = re.compile(rb"(?:\b|\s)[_\W]{0,3}x?x[_\W]{0,3}[a4\xE0-\xE6@][_\W]{0,3}n[_\W]{0,3}[ea4\xE1\xE2\xE3@][_\W]{0,3}xx?_{0,3}\b", re.IGNORECASE)
__DRUGS_ANXIETY2 = re.compile(rb"\bAlprazolam\b", re.IGNORECASE)
__DRUGS_ANXIETY3 = re.compile(rb"(?:\b|\s)[_\W]{0,3}(?:\\\/|V)[_\W]{0,3}[a4\xE0-\xE6@][_\W]{0,3}[l|][_\W]{0,3}[i1!|l\xEC-\xEF][_\W]{0,3}[u\xB5\xF9-\xFC][_\W]{0,3}m\b", re.IGNORECASE)
__DRUGS_ANXIETY4 = re.compile(rb"\b_{0,3}D[_\W]?[i1!|l\xEC-\xEF][_\W]?[a4\xE0-\xE6@][_\W]?z[_\W]?[ea3\xE9\xEA\xEB][_\W]?p[_\W]?[a4\xE0-\xE6@][_\W]?m_{0,3}\b", re.IGNORECASE)
__DRUGS_ANXIETY5 = re.compile(rb"(?:\b|\s)[a4\xE0-\xE6@][_\W]?t[_\W]?[i1!|l\xEC-\xEF][_\W]?v[_\W]?[a4\xE0-\xE6@][_\W]?n_{0,3}\b", re.IGNORECASE)
__DRUGS_ANXIETY6 = re.compile(rb"\b_{0,3}l[_\W]?[o0\xF2-\xF6][_\W]?r[_\W]?[a4\xE0-\xE6@][_\W]?z[_\W]?[e3\xE8-\xEB][_\W]?p[_\W]?[a4\xE0-\xE6@][_\W]?m_{0,3}\b", re.IGNORECASE)
__DRUGS_ANXIETY7 = re.compile(rb"\b_{0,3}c[_\W]?l[_\W]?[o0\xF2-\xF6][_\W]?n[_\W]?[a4\xE0-\xE6@][_\W]?z[_\W]?e[_\W]?p[_\W]?[a4\xE0-\xE6@][_\W]?m\b", re.IGNORECASE)
__DRUGS_ANXIETY8 = re.compile(rb"\bklonopin\b", re.IGNORECASE)
__DRUGS_ANXIETY9 = re.compile(rb"\brivotril\b", re.IGNORECASE)
DRUGS_SMEAR1 = re.compile(rb"(?:Viagra|Valium|Xanax|Soma|Cialis){2}", re.IGNORECASE)
__freemail_safe_fwd = re.compile(rb"---\s?(?:(?:Forwarded|Original) message|Alkuper.inen viesti)", re.IGNORECASE)
__JAPANESE_UCE_BODY = re.compile(rb"(?:L\$>5Bz|EE;R%a!<%k)(?:8x|9-)9p", re.IGNORECASE)
__HIGHBITS = re.compile(rb"(?:[\x80-\xff].?){4}", re.IGNORECASE)
































































REMOVE_BEFORE_LINK = re.compile(rb"m{(?:nothanks|notinterested|unsubscribehere).{0,5}http://}i", re.IGNORECASE)
GUARANTEED_100_PERCENT = re.compile(rb"100% GUARANTEED", re.IGNORECASE)
DEAR_FRIEND = re.compile(rb"^\s*Dear Friend\b", re.IGNORECASE)
DEAR_SOMETHING = re.compile(rb"\bDear (?:IT\W|Internet|candidate|sirs?|madam|investor|travell?er|car shopper|web)\b", re.IGNORECASE)
BILLION_DOLLARS = re.compile(rb"[BM]ILLION DOLLAR", re.IGNORECASE)
EXCUSE_4 = re.compile(rb"To Be Removed,?Please", re.IGNORECASE)
EXCUSE_24 = re.compile(rb"you(?:'ve|'re| have|are)? receiv(?:e|ed|ing)this(?:advertisement|offer|special|recurring|paid).{0,16}\b(?:by either|because)", re.IGNORECASE)
EXCUSE_REMOVE = re.compile(rb"to be removedfrom.{0,20}(?:mailings|offers)", re.IGNORECASE)
STRONG_BUY = re.compile(rb"strong buy", re.IGNORECASE)
STOCK_ALERT = re.compile(rb"\bstock alert", re.IGNORECASE)
NOT_ADVISOR = re.compile(rb"not a registeredinvestmentadvisor", re.IGNORECASE)
PREST_NON_ACCREDITED = re.compile(rb"prestigi?ous\b.{0,20}\bnon-accredited\b.{0,20}\buniversities", re.IGNORECASE)
BODY_ENHANCEMENT = re.compile(rb"\b(?:enlarge|increase|grow|lengthen|larger\b|bigger\b|longer\b|thicker\b|\binches\b).{0,50}\b(?:penis|maleorgan|pee[-]?pee|dick|sc?hlong|wh?anger|breast(?!\s+cancer))", re.IGNORECASE)
BODY_ENHANCEMENT2 = re.compile(rb"\b(?:penis|maleorgan|pee[-]?pee|dick|sc?hlong|wh?anger|breast(?!\s+cancer)).{0,50}\b(?:enlarge|increase|grow|lengthen|larger\b|bigger\b|longer\b|thicker\b|\binches\b|size)", re.IGNORECASE)
IMPOTENCE = re.compile(rb"\b(?:impotence (?:problem|cure|solution)|Premature Ejaculation|erectile dysfunction)", re.IGNORECASE)
NA_DOLLARS = re.compile(rb"\b(?:\d{1,3})?Million\b.{0,40}\b(?:Canadian Dollar?s?|US\$|U\.??S\.? Dollar)", re.IGNORECASE)
US_DOLLARS_3 = re.compile(rb"(?:\$|usd).?\d{1,3}[,.]\d{3}[,.]\d{3}(?:[,.]\d\d)?", re.IGNORECASE)
MILLION_USD = re.compile(rb"Million\b.{0,40}\b(?:United States?Dollars?|USD)", re.IGNORECASE)
URG_BIZ = re.compile(rb"urgent.{0,16}(?:assistance|business|buy|confidential|notice|proposal|reply|request|response)", re.IGNORECASE)
MONEY_BACK = re.compile(rb"money back guarantee", re.IGNORECASE)
FREE_QUOTE_INSTANT = re.compile(rb"free.{0,12}(?:(?:instant|express|online|no.?obligation).{0,4})+.{0,32}\bquote", re.IGNORECASE)
BAD_CREDIT = re.compile(rb"\b(?:bad|poor|no\b|eliminate|repair|(?:re)?establish|damag).{0,10}(?:credit|debt)\b", re.IGNORECASE)
REFINANCE_YOUR_HOME = re.compile(rb"\brefinanceyour(?:current)?(?:home|house)\b", re.IGNORECASE)
REFINANCE_NOW = re.compile(rb"time torefinance|refinanc\w{1,3}\b.{0,16}\bnow\b", re.IGNORECASE)
NO_MEDICAL = re.compile(rb"\bno medicalexam", re.IGNORECASE)
DIET_1 = re.compile(rb"\b(?:(?:without|no) (?:exercis(?:e(?! price)|ing)|dieting)|weight.?loss|(?:extra|lose|lost|losing).{0,10}(?:pounds|weight|inches|lbs)|burn.{1,10}fat)\b", re.IGNORECASE)
FIN_FREE = re.compile(rb"\bfinancial(?:ly)?(?:free|independen)", re.IGNORECASE)
FORWARD_LOOKING = re.compile(rb"\bcontains forward-looking statements\b", re.IGNORECASE)
ONE_TIME = re.compile(rb"\bone\W+time(?:charge|investment|offer|promotion)", re.IGNORECASE)
JOIN_MILLIONS = re.compile(rb"\bjoin(?:millions|thousands)\b", re.IGNORECASE)
MARKETING_PARTNERS = re.compile(rb"\b(?:marketing|network)partner|\bpartner(?:web)?site", re.IGNORECASE)
LOW_PRICE = re.compile(rb"\blow.{0,4}(?:P)rice", re.IGNORECASE)
UNCLAIMED_MONEY = re.compile(rb"\bunclaimed\s(?:assets?|accounts?|mon(?:ey|ies)|balance|funds?|prizes?|rewards?|payments?|deposits?)\b", re.IGNORECASE)
OBSCURED_EMAIL = re.compile(rb"\w+\^\S+\(\w{2,4}\b", re.IGNORECASE)
BANG_OPRAH = re.compile(rb"\boprah!", re.IGNORECASE)
ACT_NOW_CAPS = re.compile(rb"\bA(?:ct) N(?:ow)\b", re.IGNORECASE)
MORE_SEX = re.compile(rb"increased?.{0,9}(?:sex|stamina)", re.IGNORECASE)
BANG_GUAR = re.compile(rb"\bguaranteed?\!", re.IGNORECASE)
__RUDE_HTML_1 = re.compile(rb"Get a capable htmle-mailer", re.IGNORECASE)
__RUDE_HTML_2 = re.compile(rb"not supportthedisplayofHTML. Please viewthismessageina different", re.IGNORECASE)
__RUDE_HTML_3 = re.compile(rb"This messagecontains an HTML formattedmessagebut youremailclient does", re.IGNORECASE)
__RUDE_HTML_4 = re.compile(rb"Your mailer do notsupportHTML messages.Switch toa better mailer", re.IGNORECASE)
INVESTMENT_ADVICE = re.compile(rb"\binvestment advice", re.IGNORECASE)
MALE_ENHANCE = re.compile(rb"male enhancement", re.IGNORECASE)
PRICES_ARE_AFFORDABLE = re.compile(rb"\baffordable.{0,10}prices\b", re.IGNORECASE)
REPLICA_WATCH = re.compile(rb"\breplica.{1,20}rolex", re.IGNORECASE)
EM_ROLEX = re.compile(rb"[^\s\w.]rolex", re.IGNORECASE)
FREE_PORN = re.compile(rb"\bfree(?:porn|xxx|adult)", re.IGNORECASE)
CUM_SHOT = re.compile(rb"\bcum[-]?shots?\b", re.IGNORECASE)
LIVE_PORN = re.compile(rb"\blive.{0,9}(?:fuck(?:ing)?|sex|naked|girls?|virgins?|teens?|porno?)\b", re.IGNORECASE)









__BOUNCE_ESMTP = re.compile(rb"^This messages wascreated automatically by mail delivery software", re.IGNORECASE)
__BOUNCE_OOO_2 = re.compile(rb"\bI ?.m away until.{10,20} and am unabletoreadyourmessage\b", re.IGNORECASE)
__BOUNCE_OOO_3 = re.compile(rb"\bI am currently outof theoffice\b", re.IGNORECASE)
__BOUNCE_NEVER_SEE = re.compile(rb"\bThis is an autoresponder. I'll neverseeyourmessage\b", re.IGNORECASE)
__BOUNCE_NONWORKING = re.compile(rb"\bYou havereacheda non.?workingaddress. Please check\b", re.IGNORECASE)
__BOUNCE_ETRUST = re.compile(rb"^eTrustSecureContentManagerSMTPMAILcouldnotdeliverthee-mail", re.IGNORECASE)
__BOUNCE_NO_RESEND = re.compile(rb"\bPlease do notresendyouroriginalmessage\.", re.IGNORECASE)
__VBOUNCE_EXIM = re.compile(rb"apotentiallyexecutableattachment", re.IGNORECASE)
__VBOUNCE_STRIP_ATTACH = re.compile(rb"\bhas strippedoneormoreattachments from thefollowing message\b", re.IGNORECASE)
__VBOUNCE_GUIN = re.compile(rb"message contains file attachments thatare not permitted", re.IGNORECASE)
__VBOUNCE_CISCO = re.compile(rb"^Found virus\S+ infile\S/m", re.IGNORECASE)
__VBOUNCE_SMTP = re.compile(rb"host \S+ said:5\d\d\s+Error: Message content rejected", re.IGNORECASE)
__VBOUNCE_AOL = re.compile(rb"TRANSACTIONFAILED- UnrepairableVirusDetected.", re.IGNORECASE)
__VBOUNCE_DUTCH = re.compile(rb"bevatte bijlage besmet welkebesmet wasmet een virus", re.IGNORECASE)
__VBOUNCE_MAILMARSHAL = re.compile(rb"Mail.?Marshal Rule:InboundMessages: BlockDangerousAttachments", re.IGNORECASE)
__VBOUNCE_VALERT = re.compile(rb"The mail message \S+ \S+ yousent to \S+ contains the virus", re.IGNORECASE)
__VBOUNCE_REJ_FILT = re.compile(rb"Reason: Rejected by filter", re.IGNORECASE)
__VBOUNCE_MAILSWEEP = re.compile(rb"MAILsweeper has found that a \S+ \S+ \S+ \S+ one or more virus", re.IGNORECASE)
__VBOUNCE_NAV3 = re.compile(rb"^Reporting-MTA: NortonAnti.?Virus Gateway", re.IGNORECASE)
__VBOUNCE_AMAVISD2 = re.compile(rb"\bV I R US\b", re.IGNORECASE)
__VBOUNCE_DOMINO2 = re.compile(rb"^Incident Information:", re.IGNORECASE)
__VBOUNCE_ATTACHMENT0 = re.compile(rb"(?:Attachment.{0,40}was Deleted|the infectedattachment)", re.IGNORECASE)
__VBOUNCE_AVREPORT0 = re.compile(rb"(antivirus systemreport|theantivirusmodulehas|illegalattachment|UnrepairableVirusDetected)", re.IGNORECASE)
__VBOUNCE_MAILSWEEP2 = re.compile(rb"\bblocked byMailsweeper\b", re.IGNORECASE)
__VBOUNCE_CLICKBANK = re.compile(rb"\bvirus scannerdeleted yourmessage\b", re.IGNORECASE)
__VBOUNCE_QUOTED_EXE = re.compile(rb"> TVqQAAMAAAAEAAAA", re.IGNORECASE)
__VBOUNCE_ATT_QUAR = re.compile(rb"\bThe attachment wasquarantined\b", re.IGNORECASE)
__VBOUNCE_SECURIQ = re.compile(rb"\bGROUP securiQ.Wall\b", re.IGNORECASE)











FUZZY_AFFORDABLE = re.compile(rb"<inter W1><postP2>(?!affordable)<A><F><F><O><R><D><A><B><L><E>", re.IGNORECASE)
FUZZY_AMBIEN = re.compile(rb"<inter W1><postP2>(?<!t)(?!ambien)(?!ombien)<A><M><B><I><E><N>", re.IGNORECASE)
FUZZY_BILLION = re.compile(rb"(?!billion)<B><I><L><L><I><O><N>", re.IGNORECASE)
FUZZY_CPILL = re.compile(rb"(?!ciali[sz])<C><I><A><L><I><S>", re.IGNORECASE)
FUZZY_CREDIT = re.compile(rb"<inter W1>(?![ck]r[e\xe9]dit)<C><R><E><D><I><T>", re.IGNORECASE)
FUZZY_ERECT = re.compile(rb"<inter W2><postP3>(?!erection)<E><R><E><C><T><I><O><N>", re.IGNORECASE)
FUZZY_GUARANTEE = re.compile(rb"<inter W1><postP2>(?!guarantee)<G><U><A><R><A><N><T><E><E>", re.IGNORECASE)
FUZZY_MEDICATION = re.compile(rb"<inter W1><postP2>(?!medicati[eo])<M><E><D><I><C><A><T><I><O><N>", re.IGNORECASE)
FUZZY_MILLION = re.compile(rb"(?!milli?[o\xf3\xd3]n)<M><I><L><L><I><O><N>", re.IGNORECASE)
FUZZY_MONEY = re.compile(rb"(?!money)<M><O><N><E><Y>", re.IGNORECASE)
FUZZY_MORTGAGE = re.compile(rb"<inter W1><postP2>(?!mortgage)<M><O><R><T><G><A><G><E>", re.IGNORECASE)
FUZZY_OBLIGATION = re.compile(rb"<inter W1><postP2>(?!obligation)<O><B><L><I><G><A><T><I><O><N>", re.IGNORECASE)
FUZZY_OFFERS = re.compile(rb"(?!offers)<O><F><F><E><R><S>", re.IGNORECASE)
FUZZY_PHARMACY = re.compile(rb"<inter W2><postP2>(?!pharmacy)<P><H><A><R><M><A><C><Y>", re.IGNORECASE)
FUZZY_PHENT = re.compile(rb"<inter W1><postP2>(?!phentermine)<P><H><E><N><T><E><R><M><I><N><E>", re.IGNORECASE)
FUZZY_PRESCRIPT = re.compile(rb"<inter W2><postP2>(?!prescription)<P><R><E><S><C><R><I><P><T><I><O><N>", re.IGNORECASE)
FUZZY_PRICES = re.compile(rb"<inter W2><postP2>(?!price)<P><R><I><C><E><S>", re.IGNORECASE)
FUZZY_REFINANCE = re.compile(rb"<inter W2><postP2>(?!refinance)<R><E><F><I><N><A><N><C><E>", re.IGNORECASE)
FUZZY_REMOVE = re.compile(rb"(?!remove)<R><E><M><O><V><E>", re.IGNORECASE)
FUZZY_ROLEX = re.compile(rb"(?!rolex)<R><O><L><E><X>", re.IGNORECASE)
FUZZY_SOFTWARE = re.compile(rb"(?!software)<S><O><F><T><W><A><R><E>", re.IGNORECASE)
FUZZY_THOUSANDS = re.compile(rb"(?!thousands)<T><H><O><U><S><A><N><D><S>", re.IGNORECASE)
FUZZY_VLIUM = re.compile(rb"<inter W1><postP2>(?!valium|verifiquem|volturno|vollum)<V><A><L><I><U><M>", re.IGNORECASE)
FUZZY_VIOXX = re.compile(rb"<inter W1><postP2>(?!vioxx)<V><I><O><X><X>", re.IGNORECASE)
FUZZY_VPILL = re.compile(rb"(?!viagra)<V><I><A><G><R><A>", re.IGNORECASE)
FUZZY_XPILL = re.compile(rb"<inter W3><postP2>(?!xanax)<X><A><N><A><X>", re.IGNORECASE)
AXB_3LITTLE_PIGS = re.compile(rb"\bwas sentbythird-partyindependentmarketingagent\.", re.IGNORECASE)
AXB_BODYMAIL_SBL112884 = re.compile(rb"\@yeah\.net\b", re.IGNORECASE)
BANKING_LAWS = re.compile(rb"banking laws", re.IGNORECASE)
CN_B2B_SPAMMER = re.compile(rb"\bWeare(?:(?:a )?(?:China|Taiwan)[-\s]based|(?:oneof(?:the)?best|(?:a)?leading)[^\.]{10,90}(?:in|from)(?:China|Taiwan))\b", re.IGNORECASE)
CURR_PRICE = re.compile(rb"\bCurrent Price:", re.IGNORECASE)
DEAR_BENEFICIARY = re.compile(rb"\b(?:De[ae]r\s|At+(?:ention|n):?\s?)(?:\S+\s)?Ben[ei]ficiary\b", re.IGNORECASE)
DEAR_EMAIL_USER = re.compile(rb"^\s?(?:Dear\s|Attention:?\s?)(?:E|Web)-?mail\s(?:account\s)?User\b", re.IGNORECASE)
DEAR_WINNER = re.compile(rb"\bdear.{1,20}winner", re.IGNORECASE)
EMRCP = re.compile(rb"\bExcess Maximum ReturnCapital Profit\b", re.IGNORECASE)
FRT_ADOBE2 = re.compile(rb"<inter W0><postP2>\b(?!adobe)<A><D><O><B><E>\b", re.IGNORECASE)
FRT_APPROV = re.compile(rb"<inter sP2><postP2>\b(?!approu?v)<A><P><P><R><O><V>", re.IGNORECASE)
FRT_BIGGERMEM1 = re.compile(rb"<inter SP2><postP2>(?:<B><IX><GX><GX><E><R>|<L><A><R><GX><E><R>).{1,8}(?:<P><E><N><IX><SX>|<B><R><E><A><SX><TX>|<M><E><M><B><E><R>)", re.IGNORECASE)
FRT_OFFER2 = re.compile(rb"<inter W0><postP2>\b(?!offer)<O><F><F><E><R>", re.IGNORECASE)
FRT_PENIS1 = re.compile(rb"<interSP2><postP2>\b(?!pen\s?(?:ie?s|ny[']?s))<P><E><N><IX><SX>\b", re.IGNORECASE)
FRT_PRICE = re.compile(rb"<inter SP2><postP2>\b(?!price)<P><R><IX><C><E>\b", re.IGNORECASE)
FRT_ROLEX = re.compile(rb"<inter SP2><postP2>\b(?!rolex)<R><O><L><E><X>", re.IGNORECASE)
FUZZY_MERIDIA = re.compile(rb"<inter W3><postP2>\b(?!meridia)<M><E><R><I><D><I><A>\b", re.IGNORECASE)
HK_SCAM_N1 = re.compile(rb"\b(?:widow|son|daughter|husband|wife|brother|sister)of(?:the )?(?:late|sacked|dead|passed)\b", re.IGNORECASE)
HK_SCAM_N13 = re.compile(rb"\b(?:business|important|discreet) transaction\b", re.IGNORECASE)
HK_SCAM_N15 = re.compile(rb"\b(?:account (?:overseas?|offshore)|(?:overseas?|offshore) account)\b", re.IGNORECASE)
HK_SCAM_N2 = re.compile(rb"\bnext ofkin\b", re.IGNORECASE)
HK_SCAM_N3 = re.compile(rb"\bdirect telephonenumbers?\b", re.IGNORECASE)
HK_SCAM_N8 = re.compile(rb"\byour compensation\b", re.IGNORECASE)
HK_SCAM_S15 = re.compile(rb"(?:discovered a dormant account|can yoube my partner)", re.IGNORECASE)
HK_SCAM_S25 = re.compile(rb"\bbank (?:in|of) ghana", re.IGNORECASE)
HK_SCAM_S4 = re.compile(rb"transfer(?:this|my|of )?funds?", re.IGNORECASE)
HK_SCAM_S7 = re.compile(rb"(?:(?:investment|proposed|lucrative)(?:business|venture)|(?:business|venture) (?:enterprise|propos(?:al|ition)))", re.IGNORECASE)
LONG_TERM_PRICE = re.compile(rb"long\W+term\W+(target|projected)(\W+price)?", re.IGNORECASE)
LOOPHOLE_1 = re.compile(rb"loop-?hole inthebanking", re.IGNORECASE)
SHORT_TERM_PRICE = re.compile(rb"short\W+term\W+(target|projected)(\W+price)?", re.IGNORECASE)
TVD_ACT_193 = re.compile(rb"\bact of (?:193|nineteen thirty)", re.IGNORECASE)
TVD_APPROVED = re.compile(rb"you.{1,2}re.{0,20}approved", re.IGNORECASE)
TVD_DEAR_HOMEOWNER = re.compile(rb"^dear homeowner", re.IGNORECASE)
TVD_FUZZY_DEGREE = re.compile(rb"<inter W1><postP1>\b(?!degree)<D><E><G><R><E><E>\b", re.IGNORECASE)
TVD_FUZZY_FINANCE = re.compile(rb"(?!finance)<F><I><N><A><N><C><E>", re.IGNORECASE)
TVD_FUZZY_FIXED_RATE = re.compile(rb"<inter W2><post P2>(?!fixed rate)<F><I><X><E><D>\s+<R><A><T><E>", re.IGNORECASE)
TVD_FUZZY_MICROCAP = re.compile(rb"<inter W2><postP2>(?!microcap)(?!micro-cap)<M><I><C><R><O>-?<C><A><P>", re.IGNORECASE)
TVD_FUZZY_PHARMACEUTICAL = re.compile(rb"<inter W2><postP2>(?!pharmaceutical)<P><H><A><R><M><A><C><E><U><T><I><C><A><L>", re.IGNORECASE)
TVD_FUZZY_SYMBOL = re.compile(rb"<inter W2><postP2>(?!symbol)<S><Y><M><B><O><L>", re.IGNORECASE)
TVD_INCREASE_SIZE = re.compile(rb"\bsizeof.{1,20}(?:penis|dick|manhood)", re.IGNORECASE)
TVD_LINK_SAVE = re.compile(rb"\blink tosave\b", re.IGNORECASE)
TVD_PH_REC = re.compile(rb"\byour.{0,40}account .{0,40}record", re.IGNORECASE)
TVD_PH_SEC = re.compile(rb"\byour.{0,40}account .{0,40}security", re.IGNORECASE)
TVD_QUAL_MEDS = re.compile(rb"\bquality med(?:ication)?s\b", re.IGNORECASE)
TVD_SECTION = re.compile(rb"\bSection(?:27A|21B)", re.IGNORECASE)
TVD_SILLY_URI_OBFU = re.compile(rb"m!https?://[a-z0-9-]+\.[a-z0-9-]*\.?[^a-z0-9.:/\s\"'\@?\)>-]+[a-z0-9.-]*[a-z]{3}(?:\s|$)!i", re.IGNORECASE)
TVD_VISIT_PHARMA = re.compile(rb"Online Ph.rmacy", re.IGNORECASE)
T_FRT_ABSOLUT = re.compile(rb"<inter SP2><postP2>\b(?!absolutely)<A><B><SX><O><L><U><TX><E><L><Y>", re.IGNORECASE)
T_FRT_ADULT2 = re.compile(rb"<inter W0><postP2>\b(?!adult)<A><D><UX><L><TX>", re.IGNORECASE)
T_FRT_BEFORE = re.compile(rb"<inter SP2><postP2>\b(?!before)<B><E><F><O><R><E>\b", re.IGNORECASE)
T_FRT_BELOW2 = re.compile(rb"<inter W0><postP2>\b(?!below)<B><E><L><O><WX>\b", re.IGNORECASE)
T_FRT_CANSPAM = re.compile(rb"<inter SP2><postP2>\b(?!CAN<SP>SPAM)<C><A><N><SP><SX><P><A><M>", re.IGNORECASE)
T_FRT_CLICK = re.compile(rb"<post P2>\b(?!click)<C><L><IX><C><K>\b", re.IGNORECASE)
T_FRT_COCK = re.compile(rb"<inter SP2><postP2>\b(?![cs]ock)<C><O><C><K>", re.IGNORECASE)
T_FRT_CONTACT = re.compile(rb"<inter SP2><postP2>\b(?!contr?act)<C><O><N><TX><A><C><TX>", re.IGNORECASE)
T_FRT_ERECTION = re.compile(rb"<inter SP2><postP2>(?!erection)<E><R><E><C><TX><IX><O><N>", re.IGNORECASE)
T_FRT_ESTABLISH = re.compile(rb"<inter SP2><postP2>\b(?!estabi?lish)<E><SX><TX><A><B><L>IX><SX><H>", re.IGNORECASE)
T_FRT_EXPERIENCE = re.compile(rb"<inter SP2><postP2>\b(?!exp[e\xe9\xc9]rience)<E><X><P><E><R><IX><E><N><C><E>\b", re.IGNORECASE)
T_FRT_FOLLOW1 = re.compile(rb"<inter SP2><postP2>\b(?!follow)<F><O><L><L><O><WX>", re.IGNORECASE)
T_FRT_FOLLOW2 = re.compile(rb"<inter W0><postP2>\b(?!follow)<F><O><L><L><O><WX>", re.IGNORECASE)
T_FRT_FREE = re.compile(rb"<inter SP2><postP2>\b(?!free)<F><R><E><E>\b", re.IGNORECASE)
T_FRT_FRIEND = re.compile(rb"<inter SP2><postP2>\b(?!friend)<F><R><IX><E><N><D>", re.IGNORECASE)
T_FRT_FUCK1 = re.compile(rb"<inter SP2><postP2>\b(?!fuck)<F><U><C><K>", re.IGNORECASE)
T_FRT_HEALTH = re.compile(rb"<inter SP2><postP2>\b(?!health)<H><E><A><L><TX><H>\b", re.IGNORECASE)
T_FRT_HOUR = re.compile(rb"<inter SP2><postP2>\b(?!hour)<H><O><U><R>\b", re.IGNORECASE)
T_FRT_INCOME = re.compile(rb"<inter SP2><postP2>\b(?!income)<IX><N><C><O><M><E>\b", re.IGNORECASE)
T_FRT_INTEREST = re.compile(rb"<inter SP2><postP2>\b(?!interest)<IX><N><TX><E><R><E><SX><TX>\b", re.IGNORECASE)
T_FRT_LITTLE = re.compile(rb"<inter SP2><postP2>\b(?!little)<L><IX><TX><TX><L><E>", re.IGNORECASE)
T_FRT_LOLITA1 = re.compile(rb"<inter SP2><postP2>\b(?!lolita)<L><O><L><IX><TX><A>", re.IGNORECASE)
T_FRT_OPPORTUN1 = re.compile(rb"<inter SP2><postP2>(?!opportun)<O><P><P><O><R><TX><U><N>", re.IGNORECASE)
T_FRT_PACKAGE = re.compile(rb"<inter SP2><postP2>\b(?!package)<P><A><C><K><A><GX><E>", re.IGNORECASE)
T_FRT_PAYMENT = re.compile(rb"<inter W0>\b(?!payment)<P><A><Y><M><E><N><TX>", re.IGNORECASE)
T_FRT_PHARMAC = re.compile(rb"<inter W0><postP2>(?!pharma[c\@])<P><H><A><R><M><A><C>", re.IGNORECASE)
T_FRT_POSSIBLE = re.compile(rb"<inter SP2><postP2>\b(?!possible)<P><O><SX><SX><IX><B><L><E>\b", re.IGNORECASE)
T_FRT_PROFILE1 = re.compile(rb"<inter SP2><postP2>\b(?!profile)<P><R><O><F><IX><L><E>", re.IGNORECASE)
T_FRT_PROFILE2 = re.compile(rb"<inter W0><postP2>\b(?!profile)<P><R><O><F><IX><L><E>", re.IGNORECASE)
T_FRT_PROFIT1 = re.compile(rb"<inter SP2><postP2>\b(?!profit)<P><R><O><F><IX><TX>", re.IGNORECASE)
T_FRT_PROFIT2 = re.compile(rb"<inter W0><postP2>\b(?!profit)<P><R><O><F><IX><TX>", re.IGNORECASE)
T_FRT_PUSSY = re.compile(rb"<inter SP2><postP2>\b(?!pussy)<P><U><SX><SX><Y>", re.IGNORECASE)
T_FRT_SLUT = re.compile(rb"<inter SP2><postP2>\b(?!slut)<SX><L><U><TX>", re.IGNORECASE)
T_FRT_STOCK1 = re.compile(rb"<inter SP2><postP2>\b(?!stock)<SX><TX><O><C><K>", re.IGNORECASE)
T_FRT_STOCK2 = re.compile(rb"<inter W0><postP2>\b(?!stor?ck)<SX><TX><O><C><K>", re.IGNORECASE)
T_FRT_VIRGIN1 = re.compile(rb"<inter SP2><postP2>(?!virgin)<V><IX><R><GX><IX><N><SX>?\b", re.IGNORECASE)
T_FUZZY_SPRM = re.compile(rb"<inter W1><postP2><S><P><U><R><M>", re.IGNORECASE)
T_LFUZ_PWRMALE = re.compile(rb"<inter W1><postP2><P><O><W><E><R><M><A><L><E>", re.IGNORECASE)
T_TVD_FUZZY_SECTOR = re.compile(rb"(?!sector)<S><E><C><T><O><R>", re.IGNORECASE)
T_TVD_FUZZY_SECURITIES = re.compile(rb"<inter W2><postP2>(?!securities)<S><E><C><U><R><I><T><I><E><S>", re.IGNORECASE)
URI_OBFU_WWW = re.compile(rb"(?<!http:\/\/)\b_*w{2,3}(?!\.[-\w]+\.(?:com|net|org|biz|info))[^[:alnum:]]{1,3}(?:<D><O><T>+[^[:alnum:]]{1,3})?[[:alnum:]][-\w]{1,20}[[:alnum:]][^[:alnum:]]{1,3}(?:<D><O><T>+[^[:alnum:]]{1,3})?(?:c\s?o\s?m|n\s?e\s?t|o\s?r\s?g|b\s?i\s?z|i\s?n\s?f\s?o)_*\b", re.IGNORECASE)
__ACH_CANCELLED_01 = re.compile(rb"\b(?:(?:ACH)|dividend)[-_](?:payment|transfer|transaction|was)[-_](?:(?:was|is)[-_])?(?:rejected|cancel+ed|declined|disabled|not[-_]accepted|(?:technical)?error)", re.IGNORECASE)
__ACH_CANCELLED_02 = re.compile(rb"(?:rejected|cancel+ed|declined|your)[-_ ](?:(?:ACH)|direct[-_ ]deposit)[-_](?:payment|transfer|transaction|declin(?:ed|ing))", re.IGNORECASE)
__ACH_CANCELLED_03 = re.compile(rb"\bwire[-_]?(?:payment|transfer|transaction)[-_](?:(?:was|is)[-_])?(?:rejected|cancel+ed|declined|disabled|not[-_]accepted|(?:technical)?error)", re.IGNORECASE)
__ACH_CANCELLED_04 = re.compile(rb"\bregarding[-_ ]your[-_]direct[-_]deposit[-_]via[-_](?:ACH)", re.IGNORECASE)
__AFF_004470_NUMBER = re.compile(rb"(?:\+|00|011)\W{0,3}44\W{0,3}0?\W{0,3}70", re.IGNORECASE)
__AFF_LOTTERY = re.compile(rb"(?:lottery|winner)", re.IGNORECASE)
__AFR_UNION = re.compile(rb"\bafrican\sunion\b", re.IGNORECASE)
__AGREED_RATIO = re.compile(rb"\b(?:agreed|sharing)\s(?:ratios?|percent\w+)\b", re.IGNORECASE)
__AM_DYING = re.compile(rb"\b(?:am\s(?:\S+\s)?dying|terminally\sill|cancer|en\sphase\sterminale|(?:become|is|devenu|maladie)\sincurable|que\sje\smeurs)\b", re.IGNORECASE)
__ATM_CARD = re.compile(rb"\b(?:your|the|this|through|via|by\smeans\sof\|that\sa)[\s\(](?:\w{1,20}\s)?(?:atm|debit|(?:money[\s-]?gram\s)?fast\scash)(?:\smaster|swift|value?|cash)?[\s\)]card", re.IGNORECASE)
__ATTN_MAIL_USER = re.compile(rb"\b(?:att(?:entio)?n|dear|caro) (?:web ?(?:mail)?\s\S\s)?(?:web ?|e-?)?mail (?:user|DO USU(?:=E1|[\xe1]|[\xc3][\xa1])RIO)[:;,]", re.IGNORECASE)
__BACK_SCRATCH = re.compile(rb"\bmutual+y?\s(?:benefi(?:t|cial)|interest)\b", re.IGNORECASE)
__BANK_DRAFT = re.compile(rb"\bbank\sdraft", re.IGNORECASE)
__BARRISTER = re.compile(rb"\b(?:barrister|solicitor at law|barr\.)", re.IGNORECASE)
__BENEFICIARY = re.compile(rb"\bb(?:e|=E9|[\xe9]|[\xc3][\xa9])n(?:e|=E9|[\xe9]|[\xc3][\xa9])fi(?:c|sh)i?ai?r(?:y|ies|es?)", re.IGNORECASE)
__BENIN = re.compile(rb"\bb(?:e|=E9|[\xe9]|[\xc3][\xa9])nin\b", re.IGNORECASE)
__BIGNUM_EMAILS = re.compile(rb"\b(?:thousand|million|\d[,\d]{4,})\s(?:(?!and|or|your)\w+\s)?(?:e-?mail\saddresses|leads|names)\b", re.IGNORECASE)
__BODY_STARTS_WITH_FROM_LINE = re.compile(rb"^From \S+\S\S\S\S\S\S.. ..:..:.. \S+\s+\S+\:/s", re.IGNORECASE)
__BODY_XHTML = re.compile(rb"<x-html>", re.IGNORECASE)
__BURKINA_FASO = re.compile(rb"\bburkina\s?faso\b", re.IGNORECASE)
__CAN_HELP = re.compile(rb"\bcan help\b", re.IGNORECASE)
__CASHPRZ = re.compile(rb"cash prizeof", re.IGNORECASE)
__CHARITY = re.compile(rb"\b(?:charit(?:y|[ai]ble)|orphans?|homeless|orphelins|sans\sabri)\b", re.IGNORECASE)
__CLEAN_MAILBOX = re.compile(rb"\b(?:(?:e-?mail|mail\s?box|violation:|(?:CLICK)) (?:quota size|clean(?:-?up))|clean?upclick?here)\b", re.IGNORECASE)
__COMPENSATION = re.compile(rb"\b(?:compensat(?:e|ion)|recompensed?|ausgleich)\b", re.IGNORECASE)
__CONTACT_ATTY = re.compile(rb"\bcontact(?:er)?\s(?:my|(?:de\s)?mon)\s(?:barrister|attou?rney|lawyer|avocat|gestionnaire)\b", re.IGNORECASE)
__CONTACT_YOU = re.compile(rb"\b(?:contact(?:ing)\syou|vous\scontacter?)\b", re.IGNORECASE)
__COURIER = re.compile(rb"\bcourier\s(?:company|service)\b", re.IGNORECASE)
__DBLCLAIM = re.compile(rb"avoid doubleclaiming", re.IGNORECASE)
__DEAD_PARENT = re.compile(rb"\b(?:my|meu)\s(?:(?:deceased|dead)\s(?:father|mother|husband)|(?:father|dad|mother|mom|husband|marido)(?:'?s)?\s(?:death|died|passed\saway|murder|was\s(?:killed|murdered|poisoned)|faleceu))", re.IGNORECASE)
__DEAL = re.compile(rb"\b(?:(?:business|financial|this|the|mutual|die(?:se)?r?|cette|profitable)\s(?:deal|transa[ck]tion|proposal|off[er]{2}|venture|suggestion|partnership)|your\spartnership)", re.IGNORECASE)
__DECEASED = re.compile(rb"\b(?:the|my|der|du|le|meu?)\s(?:deceased|late|verstorbenen|d(?:i|e|=E9|[\xe9]|[\xc3][\xa9])funto?|d(?:e|=E9|[\xe9]|[\xc3][\xa9])nt|falecido)\b", re.IGNORECASE)
__DESTROY_ME = re.compile(rb"\b(?:destroy|hunt|quemar)\sm[eyi]\b", re.IGNORECASE)
__DIED_IN = re.compile(rb"\bdied\sin\b", re.IGNORECASE)
__DIPLOMATIC = re.compile(rb"\bdiplomatic\b", re.IGNORECASE)
__DLND_ATTACH = re.compile(rb"\bdownload\sthe\sattach(?:ed|ment)\b", re.IGNORECASE)
__DORMANT_ACCT = re.compile(rb"\b(?:(?:dormant|abandoned|left\s?over)\s(?:account|fund|transaction|sum|deposit)|fonds\sdorment)", re.IGNORECASE)
__DOS_BODY_FRI = re.compile(rb"\bfri(?:day)?\b", re.IGNORECASE)
__DOS_BODY_MON = re.compile(rb"\bmon(?:day)?\b", re.IGNORECASE)
__DOS_BODY_SAT = re.compile(rb"\bsat(?:day)?\b", re.IGNORECASE)
__DOS_BODY_STOCK = re.compile(rb"\bstock\b", re.IGNORECASE)
__DOS_BODY_SUN = re.compile(rb"\bsun(?:day)?\b", re.IGNORECASE)
__DOS_BODY_THU = re.compile(rb"\bthu(?:r(?:s(?:day)?)?)?\b", re.IGNORECASE)
__DOS_BODY_TICKER = re.compile(rb"\b[A-Z]{4}\.(?:OB|PK)\b", re.IGNORECASE)
__DOS_BODY_TUE = re.compile(rb"\btue(?:s(?:day)?)?\b", re.IGNORECASE)
__DOS_BODY_WED = re.compile(rb"\bwed(?:nesday)?\b", re.IGNORECASE)
__DOS_COMING_TO_YOUR_PLACE = re.compile(rb"I(?:am|might(?: be)?)c[a-z]?o[a-z]?m[a-z]?(?:i[a-z]?n[a-z]?g[a-z]{0,2}|edown)toy[!a-z]{2,4}r(?:city|place[a-z]{0,2}|co[a-z]?u[a-z]?n[a-z]?t[a-z]?ry) in(?:f[a-z]?e[a-z]?w|\d{1,2})(?:day|week)s", re.IGNORECASE)
__DOS_CORRESPOND_EMAIL = re.compile(rb"correspond withmeusingmyemail", re.IGNORECASE)
__DOS_DROP_ME_A_LINE = re.compile(rb"Drop mea lineat", re.IGNORECASE)
__DOS_EMAIL_DIRECTLY = re.compile(rb"(?:Email m[a-z]?e|address)direc(?:tl|lt)yat", re.IGNORECASE)
__DOS_FIN_ADVANTAGE = re.compile(rb"\bfinancial advantage", re.IGNORECASE)
__DOS_HI = re.compile(rb"^Hi,$", re.IGNORECASE)
__DOS_I_AM_25 = re.compile(rb"I a.?m25", re.IGNORECASE)
__DOS_I_DRIVE_A = re.compile(rb"I drivea", re.IGNORECASE)
__DOS_LET_GO_JOB = re.compile(rb"I was(?:let go|fired|layed off|dismissed)from a job I h(?:el|a)d for (?:2\d years|\d{3}months)", re.IGNORECASE)
__DOS_LINK = re.compile(rb"\blink\b", re.IGNORECASE)
__DOS_MEET_EACH_OTHER = re.compile(rb"(?:meet each other|[Mm]ay?be wecan meet)", re.IGNORECASE)
__DOS_MY_OLD_JOB = re.compile(rb"my oldjob", re.IGNORECASE)
__DOS_PERSONAL_EMAIL = re.compile(rb"personal emailat", re.IGNORECASE)
__DOS_STEADY_COURSE = re.compile(rb"\bsteady(?:and increasing)?course\b", re.IGNORECASE)
__DOS_STRONG_CF = re.compile(rb"\bstrong cash flow", re.IGNORECASE)
__DOS_TAKING_HOME = re.compile(rb"Taking home \d (?:digit level|figures) in \d{1,2} months", re.IGNORECASE)
__DOS_WRITE_ME_AT = re.compile(rb"[Ww].?r.?i.?t.?e meat", re.IGNORECASE)
__EARLY_DEMISE = re.compile(rb"\buntimely\sdeath\b", re.IGNORECASE)
__EX_CUSTOMER = re.compile(rb"\b(?:(?:dead|deceased|late|verstorbenen|death\sof\sthe)\s(?:[ck]lient|customer|ac+ount|invest[eo]r|beneficiary|depositor|mr\.|kunde|engr?\.?)|titulaire\sdu\scompte\sest\sd(?:e|=E9|[\xe9]|[\xc3][\xa9])c(?:e|=E9|[\xe9]|[\xc3][\xa9])d(?:e|=E9|[\xe9]|[\xc3][\xa9])|invest[eo]r\sdied|(?:e|=E9|[\xe9]|[\xc3][\xa9])tranger\sd(?:e|=E9|[\xe9]|[\xc3][\xa9])c(?:e|=E9|[\xe9]|[\xc3][\xa9])d(?:e|=E9|[\xe9]|[\xc3][\xa9])|(?:[ck]lient|customer|ac+ount|invest[eo]r|beneficiary|mr\.|kunde|engr?\.?)\s(?:[a-z]{1,10}\s)?(?:dead|deceased|verstorbenen))", re.IGNORECASE)
__FBI_BODY_SHOUT_1 = re.compile(rb"^FEDERAL BUREAU OFINVESTIGATIONS?\b", re.IGNORECASE)
__FB_CONGRADS = re.compile(rb"Congratulations", re.IGNORECASE)
__FB_COST = re.compile(rb"\bcost\b", re.IGNORECASE)
__FB_LOTTERY = re.compile(rb"lottery", re.IGNORECASE)
__FB_NATIONAL = re.compile(rb"national", re.IGNORECASE)
__FB_NUM_PERCNT = re.compile(rb"\d\s?\%", re.IGNORECASE)
__FB_S_PRICE = re.compile(rb"pri{1,2}c[a-z]?e", re.IGNORECASE)
__FB_S_STOCK = re.compile(rb"\bstock", re.IGNORECASE)
__FB_TOUR = re.compile(rb"\btour", re.IGNORECASE)
__FEES = re.compile(rb"\b(?:security|safe\w*|courier|registration|pay|paid|up-?front|processing|delivery|transfer|keeping)[\s\w]{0,15}\s(?:fee|charge)s?\b", re.IGNORECASE)
__FIFTY_FIFTY = re.compile(rb"\b(?:50|fifty)(?:%?[\/:]50%?|%|\spercent)", re.IGNORECASE)
__FOUND_YOU = re.compile(rb"\b(?:I|we)\sfound\syour?\b", re.IGNORECASE)
__FRAUD = re.compile(rb"\b(?:de)?fraud", re.IGNORECASE)
__FRAUD_IOV = re.compile(rb"\b(?:no risks?|risky?[-]{0,3}free|free ofrisks?|100%safe|v\S{1,3}lligRisikofrei ist)\b", re.IGNORECASE)
__FRAUD_PTX = re.compile(rb"\b(?:ass?ass?inat(?:ed|ion)|murder(?:e?d)?|poison(?:e?d)?|kill(?:ed|ing|ers)\b[^.]{0,99}\b(?:war veterans|rebels?)|lestueurs)\b", re.IGNORECASE)
__FRAUD_XWW = re.compile(rb"\b(?:honest(?:ly)?\sco(?:-?operat(?:e|ion)|llaborat(?:e|ion))|ehrliche\szusammenarbeit|sichere [kc]o+p[eo]ration|col+aboration\swith\sme)\b", re.IGNORECASE)
__FRT_GOLD = re.compile(rb"<inter SP2><postP2>\b(?!gold)<G><O><L><D>\b", re.IGNORECASE)
__FRT_SILVER = re.compile(rb"<inter SP2><postP2>\b(?!s[il][li]ver)<S><I><L><V><E><R>\b", re.IGNORECASE)
__F_LARGE_MONEY = re.compile(rb"\d\d\d,\d\d\d/", re.IGNORECASE)
__F_LARGE_MONEY_2 = re.compile(rb"\d\d?\s?(?:thousand|(?:m|b|tr)illion)", re.IGNORECASE)
__GHANA = re.compile(rb"\bghana\b", re.IGNORECASE)
__GIVE_MONEY = re.compile(rb"\b(?:(?:give\syou\s(?:this\s)?(?:money|fund|inheritance))|(?:donated?\s(?:\w\+\s){0,3}(?:the\ssum\sof|(?:(?:the|this|some)\s(?:money|funds?|inheritance)|to\s)(?:you|(?:(?:the|a)\s)?church|charit(?:y|ies)|humanit\w+|needy|poor|orphan(?:age)?s?|philanthropists\?)))|devousdonnercetargent|fairedondelasomme|voudraisenfairedon|tegofunduszudodom(?:=F3|[\xf3])w(?:dziecka|wdowy))\b", re.IGNORECASE)
__HAS_ANY_EMAIL = re.compile(rb"\w@\S+\.\w", re.IGNORECASE)
__HAS_WON_01 = re.compile(rb"\bque haganado\b", re.IGNORECASE)
__HK_LOTTO_1 = re.compile(rb"\b(?:(?:inter)?national|foundation|mercato|univers|euro ?million|e-?mail|euro-pw|bill?gates|swiss|prestige|cristal|am.ricaine|coca.?cola|fiduciary|department) ?lot(?:eri[ej]|t(?:ery|o))", re.IGNORECASE)
__HK_LOTTO_2 = re.compile(rb"\blot(?:eri[ej]|t(?:ery|o)) ?(?:(?:inter)?national|foundation|mercato|univers|euro ?million|e-?mail|euro-pw|bill?gates|swiss|prestige|cristal|am.ricaine|coca.?cola|fiduciary|department)", re.IGNORECASE)
__HK_LOTTO_BALLOT = re.compile(rb"\b(?:promotional|on.?line|computer|internet|e-?mail|fran.aise)(?:ballot|draw|sweepstake)", re.IGNORECASE)
__HK_LOTTO_JACKPOT = re.compile(rb"\bmega jackpot\b", re.IGNORECASE)
__HK_LOTTO_STAATS = re.compile(rb"\bstaatsloteri", re.IGNORECASE)




__HUSH_HUSH = re.compile(rb"\b(?:confiden[tc]i[ae]l(?:\b|ity\b|it(?:=E9|[\xe9]|[\xc3][\xa9]))|private\b|secr[e\xe8](?:te?|cy)\b|sensitive\b|concealed\b|obscured?\b|discre(?:et|tion)\b|very\sdiscrete|top\ssecret|vertraulich(?:en)?\b|geheim\b|priv(?:e|=E9|[\xe9]|[\xc3][\xa9]))", re.IGNORECASE)
__INHERIT_PMT = re.compile(rb"\binheritance\spayment\s", re.IGNORECASE)
__INTL_BANK = re.compile(rb"\b(?:international\s(?:\w+\s)?bank|banque\sinternationale)\b", re.IGNORECASE)
__INVEST_COUNTRY = re.compile(rb"\binvest\sin\syour?\scountry\b", re.IGNORECASE)
__INVEST_MONEY = re.compile(rb"\binvest(?:ir)?\s(?:this|ces|d[ae]s|sur ce|deces)\s(?:money|f[ou]nds?)\b", re.IGNORECASE)
__IS_LEGAL = re.compile(rb"\b(?:(?:(this|esta)\s(?:deal|offer|transac[tc]i(?:o|[\xc3][\xb3])n|proposal|exchange|arrangement|work)|it)?\s[ie]s\s(?:(?:guaranteed|completely|absolutely|perfectly|100%|very|fully)\s)?(?:legal|hitch-free|seguro|legitimate)|legitimate\sarrangement|toute?\sl(?:e|=E9|[\xe9]|[\xc3][\xa9])gale)\b", re.IGNORECASE)
__IVORY_COAST = re.compile(rb"\b(?:Cote\s?D.Ivoire|Ivory\s?Coast|Costa\sde\sMarfil)\b", re.IGNORECASE)
__I_INHERIT = re.compile(rb"\b(?:I|eu)\s[a-z\s]{0,30}(?:inherited|herdei)\b", re.IGNORECASE)
__I_WILL_YOU = re.compile(rb"\bwill(?:ed)?\s(?:[a-z\s]{0,20}(?:fortune|money|\$[\d,]+[a-z]{0,9})\s)?to\syou\b", re.IGNORECASE)
__KAM_LOTTO2 = re.compile(rb"((ticket|serial|lucky) number|secretpin?code|batch number|referencenumber|promotiondate)/is", re.IGNORECASE)
__LOCK_MAILBOX = re.compile(rb"\b(?:(?:deactivate|lock|lose ac+ess to|los[se] (?:of )?(?:important )?(?:information|mail|messages) in) (?:your )?(?:mail\s?box|(?:web ?|e-?)mail)|your (?:mail\s?box|(?:(?:web ?|e-?)mail)(?: account)?) (?:(?:will|may) be(?:come)? )?(?:in-?a(?:ctive|cess[ia]ble)|locked|disabled|deleted|removed)\b|ditt konto vara \"?deaktiverad\"?|begr(?:=E4|\xe4|[\xc3][\xa4])nsad tillg(?:=E5|[\xe5]|[\xc3][\xa5])ng till din brevl(?:=E5|[\xe5]|[\xc3][\xa5])da|contas? de (?:web ?|e-?)mail (?:ser(?:=E1|[\xe1]|[\xc3][\xa1]) (?:desativado|exclu(?:=ED|[\xed]|[\xc3][\xad])do)|(?:=E9|[\xe9]|[\xc3][\xa9]) exclu(?:=ED|[\xed]|[\xc3][\xad])do)|destruir a sua caixa de (?:correio|entrada)|tw(?:=F3|[\xf3])j konto zostaloograniczone|straci swoje e-?mail na sta[\xc5][\x82]e|konto zostanieautomatycznie wy[\xc5][\x82][\xc4][\x85]czona)", re.IGNORECASE)
__LOTTO_ADMITS_1 = re.compile(rb"\b(?:on-?line|e-?mail|ballot|(?:inter)?national|state|(?:UK|euro)[- ]?(?:mil+ions?|PW)|Canada|Microsoft|MSN|internet|mega|jackpot+|Royal Heritage|foundation|cash\sgrant|mercato|univers|staatsloterij|bill\s?gates|Olympics?|swiss|this|est[ea]|internationaux de gagnantsde)(?:\s(?!lot|swe|prom)\w{1,20}){0,3}\s?(?:lot(?:to|t+ery|eri[ea])|sweepstakes?|promo(?:tion|cao|cion)?|jackpot+)\b", re.IGNORECASE)
__LOTTO_ADMITS_2 = re.compile(rb"\b(?:free)?(?:lot(?:to|tery|erie)|sweepstakes)\s(?:(?:inter)?na[tz]ional|department|bureau|group|award|microsoft)", re.IGNORECASE)
__LOTTO_AGENT_01 = re.compile(rb"\b(?:(?:(?:the|y?our)(?:\s\w{1,20})?|contact|accredited|listed)\sclaim(?:s|ing)?(?:\sprocessing)?|fiducia\w+|reimbursement|(?:prize|international|intl|foreign|win+ing)(?:[\s,.]+(?:rem+it+ance|settlement|payment|payout|award|transfer))+|payment|payout|immunity|(?<!memory\s)grants?)\s?(?:agent|manager|officer|secretary|director|mgr\b)", re.IGNORECASE)
__LOTTO_AGENT_02 = re.compile(rb"\blot+ery[^\.]{1,40} ticketagent", re.IGNORECASE)
__LOTTO_DEPT = re.compile(rb"\b(?:claim(?:s|ing)?(?:\sprocessing)?|fiducia\w+|reimbursement|(?:international|foreign|win+ing)(?:\s(?:rem+it+ance|settlement|payment|award))+|payment|award|compensation|lot+ery)(?:\s\w+)?\s?(?:department|dept|unit|group|committee|bureau)", re.IGNORECASE)
__LOTTO_RELATED = re.compile(rb"\b(?:lot+(?:o|ery)|sweepstakes)\s(?:prize|draw(?:s|ing)?|(?:ge)?win(?:n?er|n?ing)?|jackpot+|award|fund|com+it+e+|com+is+ion|guild|promotion|promocao|program|day|online|company|(?:in)?corporat|agent|co[-,]?ordinator|team)", re.IGNORECASE)
__LOTTO_VERIFY = re.compile(rb"\bpromo\sverification", re.IGNORECASE)
__LOTTO_WINNINGS = re.compile(rb"\b(?:claim|process(?:ing)?|transfert?(?:\s\w+)?|redeem|payment|virement|zahlung|reivindicar|demandar|remise)\s(?:(?:[a-z]{1,5}\s)?(?:your|of|the|this|de|ihrer|seu|tu)\s)+(?:win+ings?|money|(?:cash\s)?prize|award|f[ou]nds?|grant|gewinne|premio|gain)\b", re.IGNORECASE)
__LOTTO_WIN_01 = re.compile(rb"\bwin+ing\s(?:prize|number|notification|draw|check|cheque|details|information|payment)", re.IGNORECASE)
__LUCKY_WINNER = re.compile(rb"\b(?:lucky|gl.cklich(?:en)?|afortunados)\s(?:(?:ge)?win+ers?|ganador(?:es)?|individuals?)\b", re.IGNORECASE)
__LUCRATIVE = re.compile(rb"\b(?:lucrative|profitable|tr[\xe8]s\ssalutaire)\b", re.IGNORECASE)
__MAILBOX_FULL = re.compile(rb"\b(?:you(?:r (?:mail\s?box|(?:e-?|web ?)mail))? (?:is (?:almost )?full|(?:quota )?ha(?:s|ve) (?:reached|exceeded|passed) (?:the|your|it'?s?) (?:size|storage|set|(?:e-?|web ?)mail|quota|folder|mail ?box)[\/\s](?:limit|quota))|over yourmail\s?box(?:size )?(?:limit|quota)|maximum mail\s?box(?:size )?(?:limit|quota) exceeded|sua(?:conta|caixa) de(?:(?:e-?|web ?)mail|correio) (?:excedeu (?:sua|o) limite|est(?:=E1|[\xe1]|[\xc3][\xa1])quasecheio))\b", re.IGNORECASE)
__MAILBOX_FULL_SE = re.compile(rb"(?:\b=F6|[\xf6]|[\xc3][\xb6])verskridit gr(?:=E4|[\xe4]|[\xc3][\xa4])nsen f(?:=F6|[\xf6]|[\xc3][\xb6])r din postl(?:=E5|[\xe5]|[\xc3][\xa5])da\b", re.IGNORECASE)
__MAIL_ACCT_ACCESS1 = re.compile(rb"\b(?:your (?:web ?|e-?)?mail (?:account|log-?in) (?:has )?been accessed|r(?:=F3|[\xf3])zne komputery zalogowaniusie)\b", re.IGNORECASE)
__MAIL_ACCT_ACCESS2 = re.compile(rb"\blo+seac+es+toyour(?:web|e-?)?mail(?:account|log-?in|box|address)\b", re.IGNORECASE)
__MILLIONS = re.compile(rb"\bmillions\sof\s(?:dollar|euro|pound)", re.IGNORECASE)
__MOVE_MONEY = re.compile(rb"\b(?:(?:receive|re-?profile|transfer(?:ring|ir|t)?|release|repatriat(?:e|ion)|rapatrier|secure|r(?:e|=E9|[\xe9]|[\xc3][\xa9])clamation|possession|virer|dona(?:te|r)|depositante|dep[\xc3][\xb3]sito)\s(?:th(?:e(?:se)?|is)|d[ae]s|sur ce|dece[st]|cet|est[eao]s?|del?)|re-?profiling|receive|re-?locat(?:e|ing)(?:\s\w{1,15})?)\s(?:of\s|your\s|the\s){0,2}(?:sums?\sof\s|inheritance\s)?(?:proceeds|funds?|money|balance|account|g[eo]ld|compte|fond[so]{1,2}|dinero|argent)\b", re.IGNORECASE)
__MY_FORTUNE = re.compile(rb"\b(?:my|his|her)\s(?:fortune|heritage)\b", re.IGNORECASE)
__NEXT_OF_KIN = re.compile(rb"\bnext[-\s]of[-\s]kin\b", re.IGNORECASE)
__NIGERIA = re.compile(rb"\bnigeria\b", re.IGNORECASE)
__NOT_DEAD_YET = re.compile(rb"\b(?:will\sinherit|que\sherede)\b", re.IGNORECASE)
__NOT_SCAM = re.compile(rb"\b(?:not\sa\sscam|(?:not|never)\sscam\syou)\b", re.IGNORECASE)
__OUR_BEHALF = re.compile(rb"\b(?:on\s(?:my|our)\sbehalf|of\sbehalf\sof)\b", re.IGNORECASE)
__PAY_YOU = re.compile(rb"\bpay\syou\b", re.IGNORECASE)
__PLS_REVIEW = re.compile(rb"\b(?:please|kindly)\s(?:(?:re)?view|see)(?:\s\w+)?\sattach(?:ed|ment)\b", re.IGNORECASE)
__RANDOM_PICK = re.compile(rb"\b(?:random(?:ly)?\s(?:\w+\s)?(?:select(?:ion|ed)|pick(?:ed)?|computer)|(?:select|pick)ed\s(?:at\s)?random(?:ly)?|(?:esco(?:g|lh)idos|seleccion) (?:aleatoria(?:mente)?|al azar))\b", re.IGNORECASE)
__SCAM = re.compile(rb"\bscam(?:m?e[dr])?s?\b", re.IGNORECASE)
__SHARE_IT = re.compile(rb"\b(?:(?:share|allocate|teilen|parteger(?:ez|ons)?|partage)\s(?:th(?:e|is)|das|les?|des)\s(?:proceeds|funds?|money|balance|account|geld|compte|fonds)|partager(?:ez|ons)? (?:avec (?:vous|moi)|ratio|suivant unpourcentage))\b", re.IGNORECASE)
__STYLE_TAG_IN_BODY = re.compile(rb"<style(?:[^>]{0,30})?>", re.IGNORECASE)
__SUBSCRIPTION_INFO = re.compile(rb"\b(?:e?newsletters?|(?:un)?(?:subscrib|register)|you(?:r| are) subscri(?:b|ption)|opt(?:.|ing)?out\b|further info|you do ?n[o']t w(?:ish|ant)|remov\w{1,3}.{1,9}\blists?\b|to yourwhite.?list)", re.IGNORECASE)
__SUM_OF_FUND = re.compile(rb"\b(?:sum|release|freigabe)\s(?:of|der)\s(?:amount|fund|investment|mittel)\b", re.IGNORECASE)
__SURVEY = re.compile(rb"\bsurvey\b", re.IGNORECASE)
__SURVIVORS = re.compile(rb"\b(?:widow|son|daughter|husband|wife|brother|sister|attorney|vi(?:=FA|[\xfa]|[\xc3][\xba])va|esposa|veuve)\s(?:of|to|do|de)\s(?:the\s)?(?:late|falecido|finales|feu|d(?:e|=E9|[\xe9]|[\xc3][\xa9])funt|mr\.?)\s\w+\b", re.IGNORECASE)
__SYSADMIN = re.compile(rb"\b(?:help?[- ]?desk|(?:(?:web ?)?mail ?|sys(?:tem )?)admin(?:istrator)|local[- ]host|(?:support|upgrade|management) (?:team|center)|message from administrator|university mail server copyright|suporte t(?:=E9|[\xe9]|[\xc3][\xa9])cnico|administradordo sistema)\b", re.IGNORECASE)
__THEY_INHERIT = re.compile(rb"\b(?:inherit\sth(?:e|is)\smoney|herede\sest[ea]\sdinero)\b", re.IGNORECASE)
__TO_YOUR_ACCT = re.compile(rb"\b(?:f[uo]nds|money|f[uo]ndo|dinheiro|bank)\s(?:\w{1,10}\s){0,4}(?:transfer(?:red)?|transferido|sont)\s(?:to|para|en)\s(?:your|sua|votre)\s(?:account|conta|pos+es+ion)", re.IGNORECASE)
__TRAVEL_AGENT = re.compile(rb"\btravel\sagen(?:t|cy)\b", re.IGNORECASE)
__TRAVEL_BUSINESS = re.compile(rb"\bbusiness\stravel\b", re.IGNORECASE)
__TRAVEL_PROFILE = re.compile(rb"\btravel+er\sprofile\b", re.IGNORECASE)
__TRAVEL_RESERV = re.compile(rb"\b(?:reservation\s(?:confirmed|number)|travel\sreservations?)\b", re.IGNORECASE)
__TRTMT_DEFILED = re.compile(rb"\bdefiled\sall\s(?:forms\sof\s)?(?:medical\s)?treatments?\b", re.IGNORECASE)
__TRUNK_BOX = re.compile(rb"\b(?:(?:trunk|metallic|proof|security|consignment)\sbox(?:es)?|sealed\ssafe|une mallettem(?:e|=E9|[\xe9]|[\xc3][\xa9])tallique)\b", re.IGNORECASE)
__TRUSTED_CHECK = re.compile(rb"\b(?:cashier'?s?|certified)\sche(?:ck|que)", re.IGNORECASE)
__TVD_PH_BODY_01 = re.compile(rb"\baccount .{0,20}placed? [io]n restricted status", re.IGNORECASE)
__TVD_PH_BODY_02 = re.compile(rb"\brecords(?:[a-z_,-]+ )+?(?:feature|(?:a|re)ward)", re.IGNORECASE)
__TVD_PH_BODY_03 = re.compile(rb"\byou(?:'ve|have)been(?:[a-z_,-]+ )+?payment", re.IGNORECASE)
__TVD_PH_BODY_04 = re.compile(rb"\bfunds?(?!transfer from)(?!from)(?!in)(?!via)(?:[a-z_,-]+)+?toyour(?:[a-z_,-]+ )*?account", re.IGNORECASE)
__TVD_PH_BODY_05 = re.compile(rb"\bthisis(?:[a-z_,-]+ )+?protect (?:[a-z_,-]+ )+?your", re.IGNORECASE)
__TVD_PH_BODY_06 = re.compile(rb"Dear[a-z]+bank(?:member|customer)", re.IGNORECASE)
__TVD_PH_BODY_07 = re.compile(rb"\bguaranteethesafetyofyour(?:[a-z_,-]+ )*?account", re.IGNORECASE)
__TVD_PH_BODY_08 = re.compile(rb"\bmultiple passwordfailures", re.IGNORECASE)
__TVD_PH_BODY_ACCOUNTS_POST = re.compile(rb"\b(?:(?:[dr]e-?)?activat[a-z]*|(?:re-?)?validate|secure|restore|confirm|update|suspend)(?!your)(?:[a-z_,-]+ )+?accounts?\b", re.IGNORECASE)
__TVD_PH_BODY_ACCOUNTS_PRE = re.compile(rb"\baccounts?(?:[a-z_,-]+ )+?(?:record[a-z]*|suspen[a-z]+|notif(?:y|ication)|updated|verifications?|credited)\b", re.IGNORECASE)
__UN = re.compile(rb"\bunited\snations?\b", re.IGNORECASE)
__UNSUB_EMAIL = re.compile(rb"\b(?:(?:un)?subscri(?:ber?|ptions?)|abuses?|opt(?:ing)?.?out)\b[-a-z_0-9.+=]{0,60}\@[a-z0-9][-a-z_0-9.]{4,20}(?:[^a-z_0-9.-]|$)", re.IGNORECASE)
__UPGR_MAILBOX = re.compile(rb"\b(?:up(?:g[ra]+d(?:e|ing)|date) (?:[hw]as\s(?:[a-z]+\s){1,5})?(?:o[nf] )?(?:your )?(?:mail\s?box|(?:web ?|e-?)mail)|(?:web ?|e-?)mail Upgrade cuenta|atualiz(?:e|ar) (?:a|sua) caixa de correio|click\S{0,10} (?:here(?:[:\.\s]{0,5}\S{0,10}http\S{10,80})?|below)(?: link)?to(?:(?:complete|finish|increase) )?(?:(?:the|this|your)\s)?(?:up(?:date|grade)|(?:web ?|e-?)?mail(?:\s?box)? (?:size|quota|limit))|utrzymania aktywnego konta)\b", re.IGNORECASE)
__VALIDATE_MAILBOX = re.compile(rb"\b(?:(?:re-?)?(?:valida(?:te|r)|confirm|set)(?:\S?(?:increase|raise))? (?:your|(?:a )?sua) (?:mail\s?box|(?:e-?)?mail quota|caixa)|confirmar(?:que )?a suaconta (?:de e-?mail|ainda est(?:=E1|[\xe1]|[\xc3][\xa1]) ativa)|wprowadz dane konta ponizej|utrzymaniaaktywnego konta e-?mail|weryfikacji konta)\b", re.IGNORECASE)
__VALIDATE_MBOX_SE = re.compile(rb"(?:\b=E5|[\xe5]|[\xc3][\xa5])terst(?:=E4|\xe4|[\xc3][\xa4])lla ditt konto\b", re.IGNORECASE)
__V_ACCOLADES = re.compile(rb"\baccolades?\b", re.IGNORECASE)
__V_ACHIEVEMENT = re.compile(rb"\bbenchmark ofachievement\b", re.IGNORECASE)
__V_BESTOFAWARD = re.compile(rb"\bBest of\w+Award", re.IGNORECASE)
__V_BIOGRAPHY = re.compile(rb"\b(?:biography|biographies|biographical)\b", re.IGNORECASE)
__V_CBNVANITY = re.compile(rb"\bContinental Broadcasting Network\b", re.IGNORECASE)
__V_DISTINGUISHED = re.compile(rb"\bdistinguished\b", re.IGNORECASE)
__V_DPHPVANITY = re.compile(rb"\bDistinguished Professionals Hardcover Publication\b", re.IGNORECASE)
__V_EXCELLENCE = re.compile(rb"\b(?:demonstrated|commitment to)excellence\b", re.IGNORECASE)
__V_EXECS_PROS = re.compile(rb"\bexecutives? (?:and|&) professionals?\b", re.IGNORECASE)
__V_HONOR_SOCIETY = re.compile(rb"\bHonor Society\b", re.IGNORECASE)
__V_INFORM_YOU = re.compile(rb"\b(?:pleased?|pleasure) to inform you\b", re.IGNORECASE)
__V_INNERCIRCLE = re.compile(rb"\bInner Circle\b", re.IGNORECASE)
__V_NOMINATION = re.compile(rb"\b(?:nominated|nomination|potential candidate)\b", re.IGNORECASE)
__V_NO_COST = re.compile(rb"\b(?:no costs?|cost-? *free|free ofcosts?|no fees?|neither cost nor obligation)\b", re.IGNORECASE)
__V_PRINCETONPRE = re.compile(rb"\bPrinceton Premier", re.IGNORECASE)
__V_PUB_DEADLINE = re.compile(rb"\bpublication deadlines?\b", re.IGNORECASE)
__V_RECOGNITION = re.compile(rb"\brecognition\b", re.IGNORECASE)
__V_REGISTRY = re.compile(rb"\bregistry\b", re.IGNORECASE)
__V_SBCAVANITY = re.compile(rb"\bSmall BusinessCommerceAssociation", re.IGNORECASE)
__V_SHMUCK = re.compile(rb"\b(?:accomplished|distinguished|exceptional|talented|calibreof)+(?:professionals?|individuals?)\b", re.IGNORECASE)
__V_USCAVANITY = re.compile(rb"\bUS CommerceAssociation", re.IGNORECASE)
__V_WHOSWHO = re.compile(rb"\bWho.s Who\b", re.IGNORECASE)
__WEBMAIL_ACCT = re.compile(rb"\byour web?mail account", re.IGNORECASE)
__WIDOW = re.compile(rb"\b(?:widow(?:e[rd])'?s?|veuve)\b", re.IGNORECASE)
__WILL_LEGAL = re.compile(rb"\b(?:codicil|last\stestament|probate|executor|intestate|bequest|mandamus)\b", re.IGNORECASE)
__WIRE_XFR = re.compile(rb"\b(?:wire|telegraph(?:ic)?|bank)\s?transfer", re.IGNORECASE)
__YOUR_BANK = re.compile(rb"\byour?\s(?:full\s)?bank(?:ing)?\sinformations?\b", re.IGNORECASE)
__YOUR_FUND = re.compile(rb"\b(?:your|ihr)\s(?:unpaid\s|win+ing\s|ap+roved\s|foreign\s|overdue\s|outstanding\s|contract\s|inheritance\s|nicht\sausbezahlten\s){0,3}(?:fund|payment|geld)\b", re.IGNORECASE)
__YOUR_PERM = re.compile(rb"\byour\spermission\b", re.IGNORECASE)
__YOUR_PROFIT = re.compile(rb"\byour?\sprofit", re.IGNORECASE)
__YOU_ASSIST = re.compile(rb"\b(?:your\sas+istan(?:ce|t)|votre\s(?:as+istance|aide))\b", re.IGNORECASE)
__YOU_HAVE_WON = re.compile(rb"you(?: \w+)? won", re.IGNORECASE)
__YOU_INHERIT = re.compile(rb"\byour\s[a-z\s]{0,30}inherit+ance\b", re.IGNORECASE)
__YOU_WON_01 = re.compile(rb"\byou(?:r|'re|'ve|'ll|\shave|\sdid)?\s(?:e-?mail\s)?(?:\w+\s){0,2}(?:a\s)?w[io]n+(?:er|ing)?(?!'t)\b", re.IGNORECASE)
__YOU_WON_02 = re.compile(rb"\bw[io]n\s(?:(?:for|by)\s)?your?\b", re.IGNORECASE)
__YOU_WON_03 = re.compile(rb"\b(?:your?|win+ing|win+ers?|beneficiaries|participants?|individuals?|address(?:es)?|accounts?|emails?)(?:\s[-a-z\s]{4,40})?\s(?:w(?:ere|as)|ha(?:ve|s) be(?:en)?)\s(?:automatically\s)?(?:(?:randomly|raffly)\s(?:selected|cho+sen|cho+sing|picked)|(?:selected|cho+sen|cho+sing|picked)\s(?:[a-z\s]{2,40}?\srandom(?:ly)?|online|lottery|computer\s(?:ballot|wahlgang))|(?:selected|cho+sen|cho+sing|picked)(?:\sas?|\sthe){0,3}\swin+er)", re.IGNORECASE)
__YOU_WON_04 = re.compile(rb"\bqu[ei]\s?(?:vous(?:[\xc3][\xaa]|=C3=AA|[\xea]|e)tes\s?gagnant|en\scons(?:e|=E9|[\xe9]|[\xc3][\xa9])quence\sgagne)\b", re.IGNORECASE)
__YOU_WON_05 = re.compile(rb"\bI won\b", re.IGNORECASE)
__hk_bigmoney = re.compile(rb"(?:EURO?|USD?|GBP|CFA|\&\#163;|[\xa3\xa4]|\$|sumof).{0,4}(?:[0-9]{3}[^0-9a-z]?[0-9]{3}|[0-9.,]{1,4}(?:M\b|(?:de)?Mil))", re.IGNORECASE)

allRegexes = [__FRAUD_DBI, __FRAUD_KJV,__FRAUD_IRJ,__FRAUD_NEB,__FRAUD_XJR,__FRAUD_DPR,__FRAUD_PTS,__FRAUD_BEP,__FRAUD_TDP,__FRAUD_GAN,__FRAUD_IRT,__FRAUD_AON,__FRAUD_WNY,__FRAUD_IPK,__FRAUD_QXX,__FRAUD_IOU,__FRAUD_EZY,__FRAUD_MLY,__FRAUD_ZFJ,__FRAUD_KDT,__FRAUD_ULK,__FRAUD_BGP,__FRAUD_FBI,__FRAUD_JBU,__FRAUD_YWW,__FRAUD_JYG,__FRAUD_XVW,__FRAUD_UUY,__FRAUD_SNT,__FRAUD_LTX,__FRAUD_JNB,__FRAUD_QFY,__FRAUD_WDR,__FRAUD_WFC,__FRAUD_AUM,__FRAUD_MCQ,__FRAUD_ETX,__FRAUD_PVN,__FRAUD_FVU,__FRAUD_CKF,__FRAUD_FCW,__FRAUD_MQO,__FRAUD_TCC,__FRAUD_GBW,__FRAUD_NRG,__FRAUD_RLX,__FRAUD_AXF,__FRAUD_THJ,__FRAUD_YQV,__FRAUD_YJA,__FRAUD_YPO,__FRAUD_UOQ,GTUBE,TRACKER_ID,WEIRD_QUOTING,EMAIL_ROT13,__LONGWORDS_A,__LONGWORDS_B,__LONGWORDS_C,DRUG_DOSAGE,DRUG_ED_CAPS,DRUG_ED_SILD,DRUG_ED_GENERIC,DRUG_ED_ONLINE,ONLINE_PHARMACY,NO_PRESCRIPTION,VIA_GAP_GRA,__DRUGS_ERECTILE_V,__DRUGS_ERECTILE_C,__DRUGS_ERECTILE_L,__DRUGS_ERECTILE1,__DRUGS_ERECTILE2,__DRUGS_ERECTILE3,__DRUGS_ERECTILE4,__DRUGS_ERECTILE5,__DRUGS_ERECTILE6,__DRUGS_ERECTILE8,__DRUGS_ERECTILE11,__DRUGS_DIET_PHEN,__DRUGS_DIET1,__DRUGS_DIET2,__DRUGS_DIET3,__DRUGS_DIET4,__DRUGS_DIET5,__DRUGS_DIET6,__DRUGS_DIET7,__DRUGS_DIET8,__DRUGS_DIET9,__DRUGS_DIET10,__DRUGS_PAIN_VICO,__DRUGS_PAIN_VIOXX,__DRUGS_PAIN_FIO,__DRUGS_PAIN1,__DRUGS_PAIN2,__DRUGS_PAIN3,__DRUGS_PAIN4,__DRUGS_PAIN5,__DRUGS_PAIN6,__DRUGS_PAIN7,__DRUGS_PAIN8,__DRUGS_PAIN9,__DRUGS_PAIN10,__DRUGS_PAIN11,__DRUGS_PAIN12,__DRUGS_PAIN13,__DRUGS_PAIN14,__DRUGS_SLEEP1,__DRUGS_SLEEP2,__DRUGS_SLEEP3,__DRUGS_SLEEP4,__DRUGS_MUSCLE1,__DRUGS_MUSCLE2,__DRUGS_MUSCLE3,__DRUGS_MUSCLE4,__DRUGS_MUSCLE5,__DRUGS_ANXIETY_XAN,__DRUGS_ANXIETY_VAL,__DRUGS_ANXIETY1,__DRUGS_ANXIETY2,__DRUGS_ANXIETY3,__DRUGS_ANXIETY4,__DRUGS_ANXIETY5,__DRUGS_ANXIETY6,__DRUGS_ANXIETY7,__DRUGS_ANXIETY8,__DRUGS_ANXIETY9,DRUGS_SMEAR1,__freemail_safe_fwd,__JAPANESE_UCE_BODY,__HIGHBITS,REMOVE_BEFORE_LINK,GUARANTEED_100_PERCENT,DEAR_FRIEND,DEAR_SOMETHING,BILLION_DOLLARS,EXCUSE_4,EXCUSE_24,EXCUSE_REMOVE,STRONG_BUY,STOCK_ALERT,NOT_ADVISOR,PREST_NON_ACCREDITED,BODY_ENHANCEMENT,BODY_ENHANCEMENT2,IMPOTENCE,NA_DOLLARS,US_DOLLARS_3,MILLION_USD,URG_BIZ,MONEY_BACK,FREE_QUOTE_INSTANT,BAD_CREDIT,REFINANCE_YOUR_HOME,REFINANCE_NOW,NO_MEDICAL,DIET_1,FIN_FREE,FORWARD_LOOKING,ONE_TIME,JOIN_MILLIONS,MARKETING_PARTNERS,LOW_PRICE,UNCLAIMED_MONEY,OBSCURED_EMAIL,BANG_OPRAH,ACT_NOW_CAPS,MORE_SEX,BANG_GUAR,__RUDE_HTML_1,__RUDE_HTML_2,__RUDE_HTML_3,__RUDE_HTML_4,INVESTMENT_ADVICE,MALE_ENHANCE,PRICES_ARE_AFFORDABLE,REPLICA_WATCH,EM_ROLEX,FREE_PORN,CUM_SHOT,LIVE_PORN,__BOUNCE_ESMTP,__BOUNCE_OOO_2,__BOUNCE_OOO_3,__BOUNCE_NEVER_SEE,__BOUNCE_NONWORKING,__BOUNCE_ETRUST,__BOUNCE_NO_RESEND,__VBOUNCE_EXIM,__VBOUNCE_STRIP_ATTACH,__VBOUNCE_GUIN,__VBOUNCE_CISCO,__VBOUNCE_SMTP,__VBOUNCE_AOL,__VBOUNCE_DUTCH,__VBOUNCE_MAILMARSHAL,__VBOUNCE_VALERT,__VBOUNCE_REJ_FILT,__VBOUNCE_MAILSWEEP,__VBOUNCE_NAV3,__VBOUNCE_AMAVISD2,__VBOUNCE_DOMINO2,__VBOUNCE_ATTACHMENT0,__VBOUNCE_AVREPORT0,__VBOUNCE_MAILSWEEP2,__VBOUNCE_CLICKBANK,__VBOUNCE_QUOTED_EXE,__VBOUNCE_ATT_QUAR,__VBOUNCE_SECURIQ,FUZZY_AFFORDABLE,FUZZY_AMBIEN,FUZZY_BILLION,FUZZY_CPILL,FUZZY_CREDIT,FUZZY_ERECT,FUZZY_GUARANTEE,FUZZY_MEDICATION,FUZZY_MILLION,FUZZY_MONEY,FUZZY_MORTGAGE,FUZZY_OBLIGATION,FUZZY_OFFERS,FUZZY_PHARMACY,FUZZY_PHENT,FUZZY_PRESCRIPT,FUZZY_PRICES,FUZZY_REFINANCE,FUZZY_REMOVE,FUZZY_ROLEX,FUZZY_SOFTWARE,FUZZY_THOUSANDS,FUZZY_VLIUM,FUZZY_VIOXX,FUZZY_VPILL,FUZZY_XPILL,AXB_3LITTLE_PIGS,AXB_BODYMAIL_SBL112884,BANKING_LAWS,CN_B2B_SPAMMER,CURR_PRICE,DEAR_BENEFICIARY,DEAR_EMAIL_USER,DEAR_WINNER,EMRCP,FRT_ADOBE2,FRT_APPROV,FRT_BIGGERMEM1,FRT_OFFER2,FRT_PENIS1,FRT_PRICE,FRT_ROLEX,FUZZY_MERIDIA,HK_SCAM_N1,HK_SCAM_N13,HK_SCAM_N15,HK_SCAM_N2,HK_SCAM_N3,HK_SCAM_N8,HK_SCAM_S15,HK_SCAM_S25,HK_SCAM_S4,HK_SCAM_S7,LONG_TERM_PRICE,LOOPHOLE_1,SHORT_TERM_PRICE,TVD_ACT_193,TVD_APPROVED,TVD_DEAR_HOMEOWNER,TVD_FUZZY_DEGREE,TVD_FUZZY_FINANCE,TVD_FUZZY_FIXED_RATE,TVD_FUZZY_MICROCAP,TVD_FUZZY_PHARMACEUTICAL,TVD_FUZZY_SYMBOL,TVD_INCREASE_SIZE,TVD_LINK_SAVE,TVD_PH_REC,TVD_PH_SEC,TVD_QUAL_MEDS,TVD_SECTION,TVD_SILLY_URI_OBFU,TVD_VISIT_PHARMA,T_FRT_ABSOLUT,T_FRT_ADULT2,T_FRT_BEFORE,T_FRT_BELOW2,T_FRT_CANSPAM,T_FRT_CLICK,T_FRT_COCK,T_FRT_CONTACT,T_FRT_ERECTION,T_FRT_ESTABLISH,T_FRT_EXPERIENCE,T_FRT_FOLLOW1,T_FRT_FOLLOW2,T_FRT_FREE,T_FRT_FRIEND,T_FRT_FUCK1,T_FRT_HEALTH,T_FRT_HOUR,T_FRT_INCOME,T_FRT_INTEREST,T_FRT_LITTLE,T_FRT_LOLITA1,T_FRT_OPPORTUN1,T_FRT_PACKAGE,T_FRT_PAYMENT,T_FRT_PHARMAC,T_FRT_POSSIBLE,T_FRT_PROFILE1,T_FRT_PROFILE2,T_FRT_PROFIT1,T_FRT_PROFIT2,T_FRT_PUSSY,T_FRT_SLUT,T_FRT_STOCK1,T_FRT_STOCK2,T_FRT_VIRGIN1,T_FUZZY_SPRM,T_LFUZ_PWRMALE,T_TVD_FUZZY_SECTOR,T_TVD_FUZZY_SECURITIES,URI_OBFU_WWW,__ACH_CANCELLED_01,__ACH_CANCELLED_02,__ACH_CANCELLED_03,__ACH_CANCELLED_04,__AFF_004470_NUMBER,__AFF_LOTTERY,__AFR_UNION,__AGREED_RATIO,__AM_DYING,__ATM_CARD,__ATTN_MAIL_USER,__BACK_SCRATCH,__BANK_DRAFT,__BARRISTER,__BENEFICIARY,__BENIN,__BIGNUM_EMAILS,__BODY_STARTS_WITH_FROM_LINE,__BODY_XHTML,__BURKINA_FASO,__CAN_HELP,__CASHPRZ,__CHARITY,__CLEAN_MAILBOX,__COMPENSATION,__CONTACT_ATTY,__CONTACT_YOU,__COURIER,__DBLCLAIM,__DEAD_PARENT,__DEAL,__DECEASED,__DESTROY_ME,__DIED_IN,__DIPLOMATIC,__DLND_ATTACH,__DORMANT_ACCT,__DOS_BODY_FRI,__DOS_BODY_MON,__DOS_BODY_SAT,__DOS_BODY_STOCK,__DOS_BODY_SUN,__DOS_BODY_THU,__DOS_BODY_TICKER,__DOS_BODY_TUE,__DOS_BODY_WED,__DOS_COMING_TO_YOUR_PLACE,__DOS_CORRESPOND_EMAIL,__DOS_DROP_ME_A_LINE,__DOS_EMAIL_DIRECTLY,__DOS_FIN_ADVANTAGE,__DOS_HI,__DOS_I_AM_25,__DOS_I_DRIVE_A,__DOS_LET_GO_JOB,__DOS_LINK,__DOS_MEET_EACH_OTHER,__DOS_MY_OLD_JOB,__DOS_PERSONAL_EMAIL,__DOS_STEADY_COURSE,__DOS_STRONG_CF,__DOS_TAKING_HOME,__DOS_WRITE_ME_AT,__EARLY_DEMISE,__EX_CUSTOMER,__FBI_BODY_SHOUT_1,__FB_CONGRADS,__FB_COST,__FB_LOTTERY,__FB_NATIONAL,__FB_NUM_PERCNT,__FB_S_PRICE,__FB_S_STOCK,__FB_TOUR,__FEES,__FIFTY_FIFTY,__FOUND_YOU,__FRAUD,__FRAUD_IOV,__FRAUD_PTX,__FRAUD_XWW,__FRT_GOLD,__FRT_SILVER,__F_LARGE_MONEY,__F_LARGE_MONEY_2,__GHANA,__GIVE_MONEY,__HAS_ANY_EMAIL,__HAS_WON_01,__HK_LOTTO_1,__HK_LOTTO_2,__HK_LOTTO_BALLOT,__HK_LOTTO_JACKPOT,__HK_LOTTO_STAATS,__HUSH_HUSH,__INHERIT_PMT,__INTL_BANK,__INVEST_COUNTRY,__INVEST_MONEY,__IS_LEGAL,__IVORY_COAST,__I_INHERIT,__I_WILL_YOU,__KAM_LOTTO2,__LOCK_MAILBOX,__LOTTO_ADMITS_1,__LOTTO_ADMITS_2,__LOTTO_AGENT_01,__LOTTO_AGENT_02,__LOTTO_DEPT,__LOTTO_RELATED,__LOTTO_VERIFY,__LOTTO_WINNINGS,__LOTTO_WIN_01,__LUCKY_WINNER,__LUCRATIVE,__MAILBOX_FULL,__MAILBOX_FULL_SE,__MAIL_ACCT_ACCESS1,__MAIL_ACCT_ACCESS2,__MILLIONS,__MOVE_MONEY,__MY_FORTUNE,__NEXT_OF_KIN,__NIGERIA,__NOT_DEAD_YET,__NOT_SCAM,__OUR_BEHALF,__PAY_YOU,__PLS_REVIEW,__RANDOM_PICK,__SCAM,__SHARE_IT,__STYLE_TAG_IN_BODY,__SUBSCRIPTION_INFO,__SUM_OF_FUND,__SURVEY,__SURVIVORS,__SYSADMIN,__THEY_INHERIT,__TO_YOUR_ACCT,__TRAVEL_AGENT,__TRAVEL_BUSINESS,__TRAVEL_PROFILE,__TRAVEL_RESERV,__TRTMT_DEFILED,__TRUNK_BOX,__TRUSTED_CHECK,__TVD_PH_BODY_01,__TVD_PH_BODY_02,__TVD_PH_BODY_03,__TVD_PH_BODY_04,__TVD_PH_BODY_05,__TVD_PH_BODY_06,__TVD_PH_BODY_07,__TVD_PH_BODY_08,__TVD_PH_BODY_ACCOUNTS_POST,__TVD_PH_BODY_ACCOUNTS_PRE,__UN,__UNSUB_EMAIL,__UPGR_MAILBOX,__VALIDATE_MAILBOX,__VALIDATE_MBOX_SE,__V_ACCOLADES,__V_ACHIEVEMENT,__V_BESTOFAWARD,__V_BIOGRAPHY,__V_CBNVANITY,__V_DISTINGUISHED,__V_DPHPVANITY,__V_EXCELLENCE,__V_EXECS_PROS,__V_HONOR_SOCIETY,__V_INFORM_YOU,__V_INNERCIRCLE,__V_NOMINATION,__V_NO_COST,__V_PRINCETONPRE,__V_PUB_DEADLINE,__V_RECOGNITION,__V_REGISTRY,__V_SBCAVANITY,__V_SHMUCK,__V_USCAVANITY,__V_WHOSWHO,__WEBMAIL_ACCT,__WIDOW,__WILL_LEGAL,__WIRE_XFR,__YOUR_BANK,__YOUR_FUND,__YOUR_PERM,__YOUR_PROFIT,__YOU_ASSIST,__YOU_HAVE_WON,__YOU_INHERIT,__YOU_WON_01,__YOU_WON_02,__YOU_WON_03,__YOU_WON_04,__YOU_WON_05,__hk_bigmoney]